LIT-Protocol/js-sdk

tools/scripts/tools.mjs
=> refactor: optimize code

tools/scripts/build.mjs, tools/scripts/pub.mjs, tools/scripts/tools.mjs
this will fix the "has incorrect peer dependency" isssue on `@lit-protocol/` packages , thanks @sarahzdev for reporting it
```
yarn add @lit-protocol/lit-node-client@2.1.41
```
=> match lerna version onBuild and remove peer deps

CHANGELOG.md
This is the change logs for the [PR#54](https://github.com/LIT-Protocol/js-sdk/pull/54)
=> chore: Change logs for sessionSigs support to remaining functions

packages/lit-node-client-nodejs/project.json
`yarn tools --dev --apps`
`yarn tools --test --e2e html`
=> Fix global name

packages/auth-browser/src/lib/auth-browser.ts, packages/auth-browser/src/lib/chains/cosmos.ts, packages/auth-browser/src/lib/chains/eth.ts, packages/auth-browser/src/lib/chains/sol.ts, packages/lit-node-client-nodejs/src/lib/lit-node-client-nodejs.ts, packages/misc/src/lib/misc.ts, packages/types/src/lib/interfaces.ts
Mainly wanted to define type for `authNeededCallback`. 
e2e tests passed for me.
=> Clean up types, add AuthCallback and AuthCallbackParams

packages/encryption/postBuild.mjs, tools/scripts/build.mjs, tools/scripts/tools.mjs, tools/scripts/utils.mjs
Fix for #LIT-73 to make npm link work locally on testing repo due to ipfs-client using :node etc.
=> feat: add post build on individual package

package.json, tools/scripts/tools.mjs, tsconfig.json
https://linear.app/litprotocol/issue/LIT-493/[js-sdk]-force-tsconfig-wildcard-src-path
=> feat: add use wildcard on tsconfig

apps/html/manual_tests_cosmos.html
Pretty small PR to fix cheqd tests.  I think it was made a little longer because of linting.
Feel free to merge this after approving.  It's pretty small and I don't need to come back to merge it
=> fix cheqd tests

lerna.json, package.json, packages/access-control-conditions/package.json, packages/auth-browser/package.json, packages/auth-helpers/package.json, packages/bls-sdk/package.json, packages/constants/package.json, packages/constants/src/lib/version.ts, packages/contracts-sdk/package.json, tools/scripts/tools.mjs, tools/scripts/utils.mjs
Sometimes when you switch branches, you will be left with empty directories when those directories don't exist in the branch that you're switching to
Add a script to show proper message when x directory is empty, and please remove them before building
=> feat: #LIT-576 check empty directories before building

packages/lit-auth-client/src/lib/providers/OtpProvider.ts
-adds `api-key` header to `verification-api` fetch requests
=> add api-key header to verification-api requests

apps/demo-email-sms-auth/src/Otp.js
- Removes static country code from email / sms demo implementation
=> remove static country code

apps/html/manual_tests.html, packages/constants/src/lib/constants/constants.ts
Manual HTML Tests for zkSync Testnet (EVM Compatible)- check `balance >= 0`
Linear: https://linear.app/litprotocol/issue/LIT-775/add-zksync-testnet
=> test: Manual test for zkSync Testnet

apps/html/manual_tests.html, packages/constants/src/lib/constants/constants.ts
Added manual test for Sepolia as we add support for it on the node side.
=> Add manual test for sepolia

apps/demo-pkp-social-auth-next-ts/src/pages/index.tsx
- fix session signature requests
=> updated session signature params

apps/demo-email-sms-auth/src/Otp.js, packages/lit-auth-client/src/lib/lit-auth-client.ts, packages/lit-auth-client/src/lib/providers/OtpProvider.ts, packages/types/src/lib/interfaces.ts
**Summary**
- Made `emailCustomizationOptions` optional
- Fixed "embedd" to "embed"
=> Fix: otp method name and optional param

apps/demo-email-sms-auth/src/Otp.css, apps/demo-email-sms-auth/src/Otp.js, packages/lit-auth-client/src/lib/lit-auth-client.ts, packages/lit-auth-client/src/lib/providers/OtpProvider.ts, packages/types/src/lib/interfaces.ts
- reverts commit 79198d9ae0ae83d009e208a7fa5a54baeac465c3.
=> Revert "Feature/lit 787 add captcha response check to lit auth client

packages/access-control-conditions/src/lib/canonicalFormatter.ts
- Adds canonical formatter logic accounting for additional properties on #161 .
=> Fix/cheqd-specific cosmos ACC canonical formatter

.github/workflows/ci.yml
=> Use setup-node GH action with yarn caching

apps/demo-lit-connect-modal-next/README.md
=> docs: update lit-connect-modal demo readme

packages/lit-node-client-nodejs/src/lib/lit-node-client-nodejs.ts
600kb reduction on bundle file size for lit-node-client-vanilla
=> [V2/V3][Feat/lit 1332]  optimise single node execution to use different algorithm

security.txt
See: https://linear.app/litprotocol/issue/LIT-2003/create-securitytxt-file-in-our-repos-so-people-can-know-where-to
=> Added security.txt

packages/contracts-sdk/src/lib/contracts-sdk.ts, packages/core/src/lib/lit-core.ts
Reverts LIT-Protocol/js-sdk#289
=> Revert "set minNodeCount to all active nodes"

packages/pkp-client/README.md
Fixes invalid example link in the PKP Client README.
Updated link works
=> fix: PKP Client examples file link in README

.github/workflows/ci.yml, e2e-nodejs/group-pkp-encryption-decryption/test-pkp-encryption-decryption-file.mjs, e2e-nodejs/group-pkp-encryption-decryption/test-pkp-encryption-decryption-string.mjs, e2e-nodejs/group-pkp-encryption-decryption/test-pkp-encryption-decryption-zip-string.mjs
This PR adds a few e2e NodeJS tests for BLS encryption / decryption
- Adds new test to e2e-nodejs
=> test/add BLS encryption and decryption e2e tests

apps/html/manual_tests.html, packages/constants/src/lib/constants/constants.ts
Support Base Sepolia on Cayenne.
Manual tests
1. https://github.com/LIT-Protocol/lit_node_admin_app/pull/43
2. https://github.com/LIT-Protocol/lit-assets/pull/872
=> feat: Support Base Sepolia on Cayenne

e2e-nodejs/group-recap/test-recap-from-lit-node-client.mjs, packages/lit-node-client-nodejs/src/lib/lit-node-client-nodejs.ts
=> Nft delegation 3

e2e-nodejs/group-pkp-encryption-decryption/test-pkp-encryption-decryption-nodes.mjs
This PR adds a test where the PKP is the wallet used to encrypt and decrypt data, without requiring the user to have a controlling wallet over it
=> Test/Encryption and decryption using the PKP as the requesting wallet

apps/html/manual_tests.html, packages/constants/src/lib/constants/constants.ts
Support scroll & add tests also for scrollAlphaTestnet.
Manual Tests
https://github.com/LIT-Protocol/lit_node_admin_app/pull/44
=> feat: Support Scroll mainnet

e2e-nodejs/group-rli/test-rli-should-fail-without-rli.mjs, packages/lit-node-client-nodejs/src/lib/lit-node-client-nodejs.ts
=> Feature/lit 2237 implement retry operations for stateless threshold endpoints feat/manzano habanero

e2e-nodejs/loader.mjs
Add minting capacity credits NFT when `MINT_NEW=true` in the CI.
=> fix: e2e requires minting capacity credits NFT

.github/workflows/ci.yml
This PR adds the CI pipeline trigger to PRs targeting `staging` branches
=> add CI run on PRs targeting staging branches

.github/workflows/ci.yml, .github/workflows/lint.yml
Always check format, not just on master or feat/ branches
=> format check on every PR/push

package.json, yarn.lock
This PR updates accs schemas version
=> update accs schemas version

packages/core/src/lib/lit-core.ts
This just fixes an error message which was showing the wrong value
=> our error message was wrong

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/general_support.yml
Fixing GitHub templates to assist support process.
Fixes: [LIT-2755](https://linear.app/litprotocol/issue/LIT-2755/create-github-templates-to-assist-support-process)
=> fix(support): Fix github bug report template

README.md, lerna.json, package.json, packages/constants/src/lib/version.ts, yarn.lock
Based on this https://github.com/LIT-Protocol/accs-schemas/pull/10 we have to also update the package version in this SDK
=> feat(version-bump): update accs-schemas package for verifyTestnet chain

packages/contracts-sdk/src/lib/contracts-sdk.ts
Fixes the port check for determining the `proto` of the `url` so we can properly switch between `http` and `https`
=> ref: fix port check

packages/lit-node-client-nodejs/src/lib/lit-node-client-nodejs.ts
fixes an issue where sessions will always expire due to the expiration not being defined. we now will use the local `expiration` which was taken from the params defined by the caller. 
tested by generating sessions and auditing the expiration with logging during the generation.
=> fix exp not respected

packages/wrapped-keys/src/lib/service-client/constants.ts, packages/wrapped-keys/src/lib/service-client/types.ts, packages/wrapped-keys/src/lib/service-client/utils.ts
=> LIT-3404 - Add Wrapped Keys support for datil-dev

local-tests/tests/wrapped-keys/util.ts, packages/constants/src/lib/constants/constants.ts
Decision was made to use short names in this PR https://github.com/LIT-Protocol/lit-assets/pull/1328#discussion_r1680840672
=> feat: use short names

packages/wasm/rust/Cargo.toml, packages/wasm/rust/src/ecdsa.rs, packages/wasm/rust/src/sev_snp.rs
Removes extra dependencies and fixes some cryptographic vulnerabilities.
I also cleaned up any clippy errors.
=> Cryptographic cleanup

local-tests/setup/tinny-config.ts, local-tests/tests/wrapped-keys/util.ts, packages/constants/src/lib/constants/constants.ts, packages/contracts-sdk/src/lib/addresses.ts, packages/contracts-sdk/src/lib/contracts-sdk.ts
add `ChronicleYellowstone` RPC & migrate `datil-test` to use it
=> feat: add `ChronicleYellowstone` RPC & migrate `datil-test` to use it

packages/bls-sdk/src/lib/bls-sdk.ts
We had a peculiar issue - if you encrypted data in a lit action, and tried to decrypt it with the SDK, it would fail in the WASM.
If you encrypted via the SDK, and decrypted via a lit action, it works.  
And obviously, encrypting then decrypting using the SDK works.  And encrypting then decrypting using a lit action works.  So what's wrong?
The issue was blsful got a version bump, and this new version was on the node but not in the WASM.  Something changed in the new version - when i deserialized the `ciphertext` from a new version (from the node) using the old bls wasm crate, i saw that the `scheme` in the ciphertext struct was set to `MessageAugmentation` but it should be `ProofOfPossession`.  I tried tweaking the scheme manually to be `ProofOfPossession` and the decryption worked!  So, …
=> new wasm for new blsful version

package.json, yarn.lock
This PR bump the patch version for the `@lit-protocol/contracts` package to resolve `.cjs` issues
=> chore(@lit-protocol/contracts): patch version

lerna.json, packages/access-control-conditions/package.json, packages/auth-browser/package.json, packages/auth-helpers/package.json, packages/bls-sdk/package.json, packages/constants/package.json, packages/constants/src/lib/version.ts, packages/contracts-sdk/package.json, packages/core/package.json, packages/crypto/package.json, packages/ecdsa-sdk/package.json, packages/encryption/package.json, packages/lit-auth-client/package.json, packages/lit-node-client-nodejs/package.json, packages/lit-node-client/package.json, packages/logger/package.json, packages/misc-browser/package.json, packages/misc/package.json, packages/nacl/package.json, packages/pkp-base/package.json, packages/pkp-client/package.json, packages/pkp-cosmos/package.json, packages/pkp-ethers/package.json, packages/pkp-sui/package.json, packages/pkp-walletconnect/package.json, packages/sev-snp-utils-sdk/package.json, packages/types/package.json, packages/uint8arrays/package.json, packages/wrapped-keys/package.json
- https://github.com/LIT-Protocol/js-sdk/pull/556
- *(@lit-protocol/contracts)* Patch version
=> Publish version 6.2.4

README.md, lerna.json, packages/access-control-conditions/package.json, packages/auth-browser/package.json, packages/auth-helpers/package.json, packages/bls-sdk/package.json, packages/constants/package.json, packages/constants/src/lib/version.ts, packages/contracts-sdk/package.json, packages/core/package.json, packages/crypto/package.json, packages/ecdsa-sdk/package.json, packages/encryption/package.json, packages/lit-auth-client/package.json, packages/lit-node-client-nodejs/package.json, packages/lit-node-client/package.json, packages/logger/package.json, packages/misc-browser/package.json, packages/misc/package.json, packages/nacl/package.json, packages/pkp-base/package.json, packages/pkp-client/package.json, packages/pkp-cosmos/package.json, packages/pkp-ethers/package.json, packages/pkp-sui/package.json, packages/pkp-walletconnect/package.json, packages/sev-snp-utils-sdk/package.json, packages/types/package.json, packages/uint8arrays/package.json, packages/wrapped-keys/package.json
- https://github.com/LIT-Protocol/js-sdk/pull/553
=> chore: update package versions to 6.3.0

package.json, yarn.lock
This PR updates the access control schemas dependency that now includes a few more chains from https://github.com/LIT-Protocol/accs-schemas/pull/14
=> feat: update access control schemas dependency

lerna.json, packages/access-control-conditions/package.json, packages/auth-browser/package.json, packages/auth-helpers/package.json, packages/bls-sdk/package.json, packages/constants/package.json, packages/constants/src/lib/version.ts, packages/contracts-sdk/package.json, packages/core/package.json, packages/crypto/package.json, packages/ecdsa-sdk/package.json, packages/encryption/package.json, packages/lit-auth-client/package.json, packages/lit-node-client-nodejs/package.json, packages/lit-node-client/package.json, packages/logger/package.json, packages/misc-browser/package.json, packages/misc/package.json, packages/nacl/package.json, packages/pkp-base/package.json, packages/pkp-client/package.json, packages/pkp-cosmos/package.json, packages/pkp-ethers/package.json, packages/pkp-sui/package.json, packages/pkp-walletconnect/package.json, packages/sev-snp-utils-sdk/package.json, packages/types/package.json, packages/uint8arrays/package.json, packages/wrapped-keys/package.json
- **(feat)** Bump `@lit-protocol/accs-schemas` package to 0.0.9 which should add `juno` and `cheqd` to cosmos chains https://github.com/LIT-Protocol/accs-schemas/pull/13
=> Publish version 6.4.1

.github/workflows/ci.yml, local-tests/setup/shiva-client.ts
Switchers our runners to Warp Build for larger runner definitions.
=> ci: change runner target

local-tests/setup/session-sigs/get-eoa-session-sigs.ts, local-tests/setup/tinny-environment.ts, local-tests/setup/tinny-person.ts, packages/core/src/lib/lit-core.ts, packages/lit-auth-client/src/lib/providers/EthWalletProvider.ts, packages/lit-node-client-nodejs/src/lib/lit-node-client-nodejs.ts
Fetch again if latest blockhash is unavailable.
=> fix: race condition on getting latest blockhash

lerna.json, packages/access-control-conditions/package.json, packages/auth-browser/package.json, packages/auth-helpers/package.json, packages/bls-sdk/package.json, packages/constants/package.json, packages/constants/src/lib/version.ts, packages/contracts-sdk/package.json, packages/core/package.json, packages/crypto/package.json, packages/ecdsa-sdk/package.json, packages/encryption/package.json, packages/lit-auth-client/package.json, packages/lit-node-client-nodejs/package.json, packages/lit-node-client/package.json, packages/logger/package.json, packages/misc-browser/package.json, packages/misc/package.json, packages/nacl/package.json, packages/pkp-base/package.json, packages/pkp-client/package.json, packages/pkp-cosmos/package.json, packages/pkp-ethers/package.json, packages/pkp-sui/package.json, packages/pkp-walletconnect/package.json, packages/sev-snp-utils-sdk/package.json, packages/types/package.json, packages/uint8arrays/package.json, packages/wrapped-keys/package.json
- Update access control schemas dependency
- test(tinny): For localchain it must use `custom` for network type in the contracts sdk constructor
- Updated sepolia rpc
- https://github.com/LIT-Protocol/js-sdk/pull/584
- https://github.com/LIT-Protocol/js-sdk/pull/587
- https://github.com/LIT-Protocol/js-sdk/pull/572
=> Publish version 6.4.2

lerna.json, packages/access-control-conditions/package.json, packages/auth-browser/package.json, packages/auth-helpers/package.json, packages/bls-sdk/package.json, packages/constants/package.json, packages/constants/src/lib/version.ts, packages/contracts-sdk/package.json, packages/core/package.json, packages/crypto/package.json, packages/ecdsa-sdk/package.json, packages/encryption/package.json, packages/lit-auth-client/package.json, packages/lit-node-client-nodejs/package.json, packages/lit-node-client/package.json, packages/logger/package.json, packages/misc-browser/package.json, packages/misc/package.json, packages/nacl/package.json, packages/pkp-base/package.json, packages/pkp-client/package.json, packages/pkp-cosmos/package.json, packages/pkp-ethers/package.json, packages/pkp-sui/package.json, packages/pkp-walletconnect/package.json, packages/sev-snp-utils-sdk/package.json, packages/types/package.json, packages/uint8arrays/package.json, packages/wrapped-keys/package.json
=> Publish version 6.4.3

packages/core/src/lib/lit-core.ts
correct supported network error message
=> fix(core): correct supported network error message

lerna.json, packages/access-control-conditions/package.json, packages/auth-browser/package.json, packages/auth-helpers/package.json, packages/bls-sdk/package.json, packages/constants/package.json, packages/constants/src/lib/version.ts, packages/contracts-sdk/package.json, packages/core/package.json, packages/crypto/package.json, packages/ecdsa-sdk/package.json, packages/encryption/package.json, packages/lit-auth-client/package.json, packages/lit-node-client-nodejs/package.json, packages/lit-node-client/package.json, packages/logger/package.json, packages/misc-browser/package.json, packages/misc/package.json, packages/nacl/package.json, packages/pkp-base/package.json, packages/pkp-client/package.json, packages/pkp-cosmos/package.json, packages/pkp-ethers/package.json, packages/pkp-sui/package.json, packages/pkp-walletconnect/package.json, packages/sev-snp-utils-sdk/package.json, packages/types/package.json, packages/uint8arrays/package.json, packages/wrapped-keys/package.json
- Add optional fields for users to override params.code
```
executeJs({
ipfsId: 'Qm...',
ipfsOptions: {
overwriteCode: true,
gatewayUrl: 'https://ipfs.io/ipfs/'
}
});
```
=> Publish version 6.4.5

lerna.json, packages/access-control-conditions/package.json, packages/auth-browser/package.json, packages/auth-helpers/package.json, packages/bls-sdk/package.json, packages/constants/package.json, packages/constants/src/lib/version.ts, packages/contracts-sdk/package.json, packages/core/package.json, packages/crypto/package.json, packages/ecdsa-sdk/package.json, packages/encryption/package.json, packages/lit-auth-client/package.json, packages/lit-node-client-nodejs/package.json, packages/lit-node-client/package.json, packages/logger/package.json, packages/misc-browser/package.json, packages/misc/package.json, packages/nacl/package.json, packages/pkp-base/package.json, packages/pkp-client/package.json, packages/pkp-cosmos/package.json, packages/pkp-ethers/package.json, packages/pkp-sui/package.json, packages/pkp-walletconnect/package.json, packages/sev-snp-utils-sdk/package.json, packages/types/package.json, packages/uint8arrays/package.json, packages/wrapped-keys/package.json
- https://github.com/LIT-Protocol/js-sdk/pull/609
=> Publish version 6.4.6

packages/lit-auth-client/src/lib/providers/EthWalletProvider.ts
This PR unifies how the `authenticate` instance and static methods defaulted values for `domain` and `origin` params, using the local values first and localhost when that fails. Basically making the static version behave like the instance one
=> feat: unify domain and origin default values in EthWalletProvider authenticate methods

package.json, yarn.lock
- Update accs-schema package version
=> chore(accs-schema): update package version to `0.0.10`

lerna.json, packages/access-control-conditions/package.json, packages/auth-browser/package.json, packages/auth-helpers/package.json, packages/bls-sdk/package.json, packages/constants/package.json, packages/constants/src/lib/version.ts, packages/contracts-sdk/package.json, packages/core/package.json, packages/crypto/package.json, packages/ecdsa-sdk/package.json, packages/encryption/package.json, packages/lit-auth-client/package.json, packages/lit-node-client-nodejs/package.json, packages/lit-node-client/package.json, packages/logger/package.json, packages/misc-browser/package.json, packages/misc/package.json, packages/nacl/package.json, packages/pkp-base/package.json, packages/pkp-client/package.json, packages/pkp-cosmos/package.json, packages/pkp-ethers/package.json, packages/pkp-sui/package.json, packages/pkp-walletconnect/package.json, packages/sev-snp-utils-sdk/package.json, packages/types/package.json, packages/uint8arrays/package.json, packages/wrapped-keys/package.json
- https://github.com/LIT-Protocol/js-sdk/pull/612
- https://github.com/LIT-Protocol/js-sdk/pull/611
=> Publish version 6.4.7

packages/constants/src/lib/constants/mappers.ts
Turn on IPFS fetch hot fix for Habanero
=> fix(ipfs): turn on habanero ipfs hotfix

lerna.json, packages/access-control-conditions/package.json, packages/auth-browser/package.json, packages/auth-helpers/package.json, packages/bls-sdk/package.json, packages/constants/package.json, packages/constants/src/lib/version.ts, packages/contracts-sdk/package.json, packages/core/package.json, packages/crypto/package.json, packages/ecdsa-sdk/package.json, packages/encryption/package.json, packages/lit-auth-client/package.json, packages/lit-node-client-nodejs/package.json, packages/lit-node-client/package.json, packages/logger/package.json, packages/misc-browser/package.json, packages/misc/package.json, packages/nacl/package.json, packages/pkp-base/package.json, packages/pkp-client/package.json, packages/pkp-cosmos/package.json, packages/pkp-ethers/package.json, packages/pkp-sui/package.json, packages/pkp-walletconnect/package.json, packages/sev-snp-utils-sdk/package.json, packages/types/package.json, packages/uint8arrays/package.json, packages/wrapped-keys/package.json
- https://github.com/LIT-Protocol/js-sdk/pull/614
=> Publish version 6.4.8

lerna.json, packages/access-control-conditions/package.json, packages/auth-browser/package.json, packages/auth-helpers/package.json, packages/bls-sdk/package.json, packages/constants/package.json, packages/constants/src/lib/version.ts, packages/contracts-sdk/package.json, packages/core/package.json, packages/crypto/package.json, packages/ecdsa-sdk/package.json, packages/encryption/package.json, packages/lit-auth-client/package.json, packages/lit-node-client-nodejs/package.json, packages/lit-node-client/package.json, packages/logger/package.json, packages/misc-browser/package.json, packages/misc/package.json, packages/nacl/package.json, packages/pkp-base/package.json, packages/pkp-client/package.json, packages/pkp-cosmos/package.json, packages/pkp-ethers/package.json, packages/pkp-sui/package.json, packages/pkp-walletconnect/package.json, packages/sev-snp-utils-sdk/package.json, packages/types/package.json, packages/uint8arrays/package.json, packages/wrapped-keys/package.json
- https://github.com/LIT-Protocol/js-sdk/pull/616
=> Publish version 6.4.9

lerna.json, packages/access-control-conditions/package.json, packages/auth-browser/package.json, packages/auth-helpers/package.json, packages/bls-sdk/package.json, packages/constants/package.json, packages/constants/src/lib/version.ts, packages/contracts-sdk/package.json, packages/core/package.json, packages/crypto/package.json, packages/ecdsa-sdk/package.json, packages/encryption/package.json, packages/lit-auth-client/package.json, packages/lit-node-client-nodejs/package.json, packages/lit-node-client/package.json, packages/logger/package.json, packages/misc-browser/package.json, packages/misc/package.json, packages/nacl/package.json, packages/pkp-base/package.json, packages/pkp-client/package.json, packages/pkp-cosmos/package.json, packages/pkp-ethers/package.json, packages/pkp-sui/package.json, packages/pkp-walletconnect/package.json, packages/sev-snp-utils-sdk/package.json, packages/types/package.json, packages/uint8arrays/package.json, packages/wrapped-keys/package.json
- #580 (+-40% speed boost on connection)
- #617
=> Publish version 6.4.10

lerna.json, packages/access-control-conditions/package.json, packages/auth-browser/package.json, packages/auth-helpers/package.json, packages/bls-sdk/package.json, packages/constants/package.json, packages/constants/src/lib/version.ts, packages/contracts-sdk/package.json, packages/core/package.json, packages/crypto/package.json, packages/ecdsa-sdk/package.json, packages/encryption/package.json, packages/lit-auth-client/package.json, packages/lit-node-client-nodejs/package.json, packages/lit-node-client/package.json, packages/logger/package.json, packages/misc-browser/package.json, packages/misc/package.json, packages/nacl/package.json, packages/pkp-base/package.json, packages/pkp-client/package.json, packages/pkp-cosmos/package.json, packages/pkp-ethers/package.json, packages/pkp-sui/package.json, packages/pkp-walletconnect/package.json, packages/sev-snp-utils-sdk/package.json, packages/types/package.json, packages/uint8arrays/package.json, packages/wrapped-keys/package.json
- https://github.com/LIT-Protocol/js-sdk/pull/636
=> Publish version 6.5.1

packages/core/src/lib/lit-core.ts
This PR updates the "connected to X of Y nodes, with a minimum of Z" as that was misleading when X>=Z. We yet do not support handshakes that do not succeed with all nodes
=> fix: clarify handshake timeout error message

packages/core/src/lib/lit-core.ts, packages/lit-node-client-nodejs/src/lib/lit-node-client-nodejs.ts
=> feat: rename getRequestId to _getNewRequestId

lerna.json, packages/access-control-conditions/package.json, packages/auth-browser/package.json, packages/auth-helpers/package.json, packages/bls-sdk/package.json, packages/constants/package.json, packages/constants/src/lib/version.ts, packages/contracts-sdk/package.json, packages/core/package.json, packages/crypto/package.json, packages/ecdsa-sdk/package.json, packages/encryption/package.json, packages/lit-auth-client/package.json, packages/lit-node-client-nodejs/package.json, packages/lit-node-client/package.json, packages/logger/package.json, packages/misc-browser/package.json, packages/misc/package.json, packages/nacl/package.json, packages/pkp-base/package.json, packages/pkp-client/package.json, packages/pkp-cosmos/package.json, packages/pkp-ethers/package.json, packages/pkp-sui/package.json, packages/pkp-walletconnect/package.json, packages/sev-snp-utils-sdk/package.json, packages/types/package.json, packages/uint8arrays/package.json, packages/wrapped-keys/package.json
=> Publish version 6.5.3

lerna.json, packages/access-control-conditions/package.json, packages/auth-browser/package.json, packages/auth-helpers/package.json, packages/bls-sdk/package.json, packages/constants/package.json, packages/constants/src/lib/version.ts, packages/contracts-sdk/package.json, packages/core/package.json, packages/crypto/package.json, packages/ecdsa-sdk/package.json, packages/encryption/package.json, packages/lit-auth-client/package.json, packages/lit-node-client-nodejs/package.json, packages/lit-node-client/package.json, packages/logger/package.json, packages/misc-browser/package.json, packages/misc/package.json, packages/nacl/package.json, packages/pkp-base/package.json, packages/pkp-client/package.json, packages/pkp-cosmos/package.json, packages/pkp-ethers/package.json, packages/pkp-sui/package.json, packages/pkp-walletconnect/package.json, packages/sev-snp-utils-sdk/package.json, packages/types/package.json, packages/uint8arrays/package.json, packages/wrapped-keys-lit-actions/package.json, packages/wrapped-keys/package.json
- https://github.com/LIT-Protocol/js-sdk/pull/642
- https://github.com/LIT-Protocol/js-sdk/pull/639
- https://github.com/LIT-Protocol/js-sdk/pull/647
- https://github.com/LIT-Protocol/js-sdk/pull/645
=> Publish version 6.6.0

packages/logger/src/lib/logger.ts
Fixes an issue with non utf8 characters being added to the `digest` which is checked for not displaying duplicate log messages.
See thread: https://litprotocol.slack.com/archives/C03TARXFRL2/p1724804636902529?thread_ts=1724779282.861389&cid=C03TARXFRL2
Ran tests for logging implementation which all pass.
=> ref: add non utf-8 character removal for hashing

packages/lit-node-client-nodejs/src/lib/lit-node-client-nodejs.ts
In addition for https://github.com/LIT-Protocol/js-sdk/pull/654, we also need to remove ecdsa from lit-node-client-nodejs
=> feat: remove `ecdsa` feature in lit-node-client-nodejs

lerna.json, packages/access-control-conditions/package.json, packages/auth-browser/package.json, packages/auth-helpers/package.json, packages/bls-sdk/package.json, packages/constants/package.json, packages/constants/src/lib/version.ts, packages/contracts-sdk/package.json, packages/core/package.json, packages/crypto/package.json, packages/ecdsa-sdk/package.json, packages/encryption/package.json, packages/lit-auth-client/package.json, packages/lit-node-client-nodejs/package.json, packages/lit-node-client/package.json, packages/logger/package.json, packages/misc-browser/package.json, packages/misc/package.json, packages/nacl/package.json, packages/pkp-base/package.json, packages/pkp-client/package.json, packages/pkp-cosmos/package.json, packages/pkp-ethers/package.json, packages/pkp-sui/package.json, packages/pkp-walletconnect/package.json, packages/sev-snp-utils-sdk/package.json, packages/types/package.json, packages/uint8arrays/package.json, packages/wrapped-keys-lit-actions/package.json, packages/wrapped-keys/package.json
- https://github.com/LIT-Protocol/js-sdk/pull/628
- https://github.com/LIT-Protocol/js-sdk/pull/651
- https://github.com/LIT-Protocol/js-sdk/pull/646
- https://github.com/LIT-Protocol/js-sdk/pull/625
- https://github.com/LIT-Protocol/js-sdk/pull/649
- https://github.com/LIT-Protocol/js-sdk/pull/657
=> chore: update package version to `6.7.0`

lerna.json, packages/access-control-conditions/package.json, packages/auth-browser/package.json, packages/auth-helpers/package.json, packages/bls-sdk/package.json, packages/constants/package.json, packages/constants/src/lib/version.ts, packages/contracts-sdk/package.json, packages/core/package.json, packages/crypto/package.json, packages/ecdsa-sdk/package.json, packages/encryption/package.json, packages/lit-auth-client/package.json, packages/lit-node-client-nodejs/package.json, packages/lit-node-client/package.json, packages/logger/package.json, packages/misc-browser/package.json, packages/misc/package.json, packages/nacl/package.json, packages/pkp-base/package.json, packages/pkp-client/package.json, packages/pkp-cosmos/package.json, packages/pkp-ethers/package.json, packages/pkp-sui/package.json, packages/pkp-walletconnect/package.json, packages/sev-snp-utils-sdk/package.json, packages/types/package.json, packages/uint8arrays/package.json, packages/wrapped-keys-lit-actions/package.json, packages/wrapped-keys/package.json
- https://github.com/LIT-Protocol/js-sdk/pull/661
- https://github.com/LIT-Protocol/js-sdk/pull/652
- https://github.com/LIT-Protocol/js-sdk/pull/665
=> Publish version 6.8.0

lerna.json, packages/access-control-conditions/package.json, packages/auth-browser/package.json, packages/auth-helpers/package.json, packages/bls-sdk/package.json, packages/constants/package.json, packages/constants/src/lib/version.ts, packages/contracts-sdk/package.json, packages/core/package.json, packages/crypto/package.json, packages/ecdsa-sdk/package.json, packages/encryption/package.json, packages/lit-auth-client/package.json, packages/lit-node-client-nodejs/package.json, packages/lit-node-client/package.json, packages/logger/package.json, packages/misc-browser/package.json, packages/misc/package.json, packages/nacl/package.json, packages/pkp-base/package.json, packages/pkp-client/package.json, packages/pkp-cosmos/package.json, packages/pkp-ethers/package.json, packages/pkp-sui/package.json, packages/pkp-walletconnect/package.json, packages/sev-snp-utils-sdk/package.json, packages/types/package.json, packages/uint8arrays/package.json, packages/wrapped-keys-lit-actions/package.json, packages/wrapped-keys/package.json
- https://github.com/LIT-Protocol/js-sdk/pull/667
=> Publish version 6.8.1

lerna.json, packages/access-control-conditions/package.json, packages/auth-browser/package.json, packages/auth-helpers/package.json, packages/bls-sdk/package.json, packages/constants/package.json, packages/contracts-sdk/package.json, packages/core/package.json, packages/crypto/package.json, packages/ecdsa-sdk/package.json, packages/encryption/package.json, packages/lit-auth-client/package.json, packages/lit-node-client-nodejs/package.json, packages/lit-node-client/package.json, packages/logger/package.json, packages/misc-browser/package.json, packages/misc/package.json, packages/nacl/package.json, packages/pkp-base/package.json, packages/pkp-client/package.json, packages/pkp-cosmos/package.json, packages/pkp-ethers/package.json, packages/pkp-sui/package.json, packages/pkp-walletconnect/package.json, packages/sev-snp-utils-sdk/package.json, packages/types/package.json, packages/uint8arrays/package.json, packages/wrapped-keys-lit-actions/package.json, packages/wrapped-keys/package.json
- https://github.com/LIT-Protocol/js-sdk/pull/673
- https://github.com/LIT-Protocol/js-sdk/pull/675
- https://github.com/LIT-Protocol/js-sdk/pull/676
- https://github.com/LIT-Protocol/js-sdk/pull/671
- https://github.com/LIT-Protocol/js-sdk/pull/673
=> Publish version 6.9.0

package.json, packages/constants/src/lib/constants/constants.ts, yarn.lock
~Blocked by~: https://github.com/LIT-Protocol/accs-schemas/pull/19
=> Add `storyProtocolTestnet`

lerna.json, packages/access-control-conditions/package.json, packages/auth-browser/package.json, packages/auth-helpers/package.json, packages/bls-sdk/package.json, packages/constants/package.json, packages/contracts-sdk/package.json, packages/core/package.json, packages/crypto/package.json, packages/ecdsa-sdk/package.json, packages/encryption/package.json, packages/lit-auth-client/package.json, packages/lit-node-client-nodejs/package.json, packages/lit-node-client/package.json, packages/logger/package.json, packages/misc-browser/package.json, packages/misc/package.json, packages/nacl/package.json, packages/pkp-base/package.json, packages/pkp-client/package.json, packages/pkp-cosmos/package.json, packages/pkp-ethers/package.json, packages/pkp-sui/package.json, packages/pkp-walletconnect/package.json, packages/sev-snp-utils-sdk/package.json, packages/types/package.json, packages/uint8arrays/package.json, packages/wrapped-keys-lit-actions/package.json, packages/wrapped-keys/package.json
- https://github.com/LIT-Protocol/js-sdk/pull/680
- https://github.com/LIT-Protocol/js-sdk/pull/686
- https://github.com/LIT-Protocol/js-sdk/pull/681
- https://github.com/LIT-Protocol/js-sdk/pull/683
=> Publish version 6.10.0

.github/CODEOWNERS
Removes myself as default reviewer
=> chore: remove self as code owner

lerna.json, packages/access-control-conditions/package.json, packages/auth-browser/package.json, packages/auth-helpers/package.json, packages/bls-sdk/package.json, packages/constants/package.json, packages/constants/src/lib/version.ts, packages/contracts-sdk/package.json, packages/core/package.json, packages/crypto/package.json, packages/ecdsa-sdk/package.json, packages/encryption/package.json, packages/lit-auth-client/package.json, packages/lit-node-client-nodejs/package.json, packages/lit-node-client/package.json, packages/logger/package.json, packages/misc-browser/package.json, packages/misc/package.json, packages/nacl/package.json, packages/pkp-base/package.json, packages/pkp-client/package.json, packages/pkp-cosmos/package.json, packages/pkp-ethers/package.json, packages/pkp-sui/package.json, packages/pkp-walletconnect/package.json, packages/sev-snp-utils-sdk/package.json, packages/types/package.json, packages/uint8arrays/package.json, packages/wrapped-keys-lit-actions/package.json, packages/wrapped-keys/package.json
- https://github.com/LIT-Protocol/js-sdk/pull/694
- https://github.com/LIT-Protocol/js-sdk/pull/693
- https://github.com/LIT-Protocol/js-sdk/pull/692
- https://github.com/LIT-Protocol/js-sdk/pull/695
=> Publish version 6.11.0

.github/workflows/ci.yml
Update token as the previous ones are now invalid.
=> fix(ci): use new regen classic token

package.json, packages/constants/src/lib/constants/constants.ts, yarn.lock
Just need to add this to constants.ts since it's already in the node.
=> add polygon amoy testnet

lerna.json, packages/access-control-conditions/package.json, packages/auth-browser/package.json, packages/auth-helpers/package.json, packages/bls-sdk/package.json, packages/constants/package.json, packages/contracts-sdk/package.json, packages/core/package.json, packages/crypto/package.json, packages/ecdsa-sdk/package.json, packages/encryption/package.json, packages/lit-auth-client/package.json, packages/lit-node-client-nodejs/package.json, packages/lit-node-client/package.json, packages/logger/package.json, packages/misc-browser/package.json, packages/misc/package.json, packages/nacl/package.json, packages/pkp-base/package.json, packages/pkp-client/package.json, packages/pkp-cosmos/package.json, packages/pkp-ethers/package.json, packages/pkp-sui/package.json, packages/pkp-walletconnect/package.json, packages/sev-snp-utils-sdk/package.json, packages/types/package.json, packages/uint8arrays/package.json, packages/wrapped-keys-lit-actions/package.json, packages/wrapped-keys/package.json
- https://github.com/LIT-Protocol/js-sdk/pull/716
=> chore: update package version to 6.11.1

lerna.json, packages/access-control-conditions/package.json, packages/auth-browser/package.json, packages/auth-helpers/package.json, packages/constants/package.json, packages/constants/src/lib/version.ts, packages/contracts-sdk/package.json, packages/core/package.json, packages/crypto/package.json, packages/encryption/package.json, packages/lit-auth-client/package.json, packages/lit-node-client-nodejs/package.json, packages/lit-node-client/package.json, packages/logger/package.json, packages/misc-browser/package.json, packages/misc/package.json, packages/nacl/package.json, packages/pkp-base/package.json, packages/pkp-cosmos/package.json, packages/pkp-ethers/package.json, packages/pkp-sui/package.json, packages/pkp-walletconnect/package.json, packages/types/package.json, packages/uint8arrays/package.json, packages/wasm/package.json, packages/wrapped-keys-lit-actions/package.json, packages/wrapped-keys/package.json
- https://github.com/LIT-Protocol/js-sdk/pull/729
- https://github.com/LIT-Protocol/js-sdk/pull/730
=> Publish version 7.0.1

lerna.json, packages/access-control-conditions/package.json, packages/auth-browser/package.json, packages/auth-helpers/package.json, packages/constants/package.json, packages/constants/src/lib/version.ts, packages/contracts-sdk/package.json, packages/core/package.json, packages/crypto/package.json, packages/encryption/package.json, packages/lit-auth-client/package.json, packages/lit-node-client-nodejs/package.json, packages/lit-node-client/package.json, packages/logger/package.json, packages/misc-browser/package.json, packages/misc/package.json, packages/nacl/package.json, packages/pkp-base/package.json, packages/pkp-cosmos/package.json, packages/pkp-ethers/package.json, packages/pkp-sui/package.json, packages/pkp-walletconnect/package.json, packages/types/package.json, packages/uint8arrays/package.json, packages/wasm/package.json, packages/wrapped-keys-lit-actions/package.json, packages/wrapped-keys/package.json
- https://github.com/LIT-Protocol/js-sdk/pull/727
=> Publish version 7.0.2

lerna.json, packages/access-control-conditions/package.json, packages/auth-browser/package.json, packages/auth-helpers/package.json, packages/bls-sdk/package.json, packages/constants/package.json, packages/constants/src/lib/version.ts, packages/contracts-sdk/package.json, packages/core/package.json, packages/crypto/package.json, packages/ecdsa-sdk/package.json, packages/encryption/package.json, packages/lit-auth-client/package.json, packages/lit-node-client-nodejs/package.json, packages/lit-node-client/package.json, packages/logger/package.json, packages/misc-browser/package.json, packages/misc/package.json, packages/nacl/package.json, packages/pkp-base/package.json, packages/pkp-client/package.json, packages/pkp-cosmos/package.json, packages/pkp-ethers/package.json, packages/pkp-sui/package.json, packages/pkp-walletconnect/package.json, packages/sev-snp-utils-sdk/package.json, packages/types/package.json, packages/uint8arrays/package.json, packages/wrapped-keys-lit-actions/package.json, packages/wrapped-keys/package.json
- https://github.com/LIT-Protocol/js-sdk/pull/732
=> V6.11.3 publish

packages/core/src/lib/lit-core.spec.ts, packages/core/src/lib/lit-core.ts
This PR is an v6 backport of #744 which builds on #732
=> feat: optimize and delay even more fallback rpcs for blockhash - v6

lerna.json, packages/access-control-conditions/package.json, packages/auth-browser/package.json, packages/auth-helpers/package.json, packages/bls-sdk/package.json, packages/constants/package.json, packages/contracts-sdk/package.json, packages/core/package.json, packages/crypto/package.json, packages/ecdsa-sdk/package.json, packages/encryption/package.json, packages/lit-auth-client/package.json, packages/lit-node-client-nodejs/package.json, packages/lit-node-client/package.json, packages/logger/package.json, packages/misc-browser/package.json, packages/misc/package.json, packages/nacl/package.json, packages/pkp-base/package.json, packages/pkp-client/package.json, packages/pkp-cosmos/package.json, packages/pkp-ethers/package.json, packages/pkp-sui/package.json, packages/pkp-walletconnect/package.json, packages/sev-snp-utils-sdk/package.json, packages/types/package.json, packages/uint8arrays/package.json, packages/wrapped-keys-lit-actions/package.json, packages/wrapped-keys/package.json
- https://github.com/LIT-Protocol/js-sdk/pull/745
=> chore: upgrade version to 6.11.4

package.json, packages/constants/src/lib/constants/constants.ts, packages/constants/src/lib/constants/mappers.ts, packages/contracts-sdk/src/lib/contracts-sdk.ts, packages/event-listener/package.json, packages/lit-node-client-nodejs/src/lib/lit-node-client-nodejs.ts, packages/types/src/lib/types.ts, packages/wasm/rust/rust-toolchain.toml, yarn.lock
add `naga-dev` support
```
DEBUG=true NETWORK=naga-dev yarn test:local --filter=testUseEoaSessionSigsToPkpSign
```
=> feat: add naga dev support

local-tests/test.ts, packages/auth-browser/src/lib/chains/eth.ts, packages/constants/src/lib/constants/constants.ts, packages/constants/src/lib/errors.ts, packages/core/src/lib/lit-core.ts, packages/lit-auth-client/src/lib/providers/BaseProvider.ts, packages/lit-node-client-nodejs/src/lib/lit-node-client-nodejs.ts, packages/types/src/lib/ILitNodeClient.ts, packages/types/src/lib/interfaces.ts, tsconfig.json
remove all code marked as `@deprecated`
=> chore: remove @deprecated code

lerna.json, packages/access-control-conditions/package.json, packages/auth-browser/package.json, packages/auth-helpers/package.json, packages/constants/package.json, packages/constants/src/lib/version.ts, packages/contracts-sdk/package.json, packages/core/package.json, packages/crypto/package.json, packages/encryption/package.json, packages/event-listener/package.json, packages/lit-auth-client/package.json, packages/lit-node-client-nodejs/package.json, packages/lit-node-client/package.json, packages/logger/package.json, packages/misc-browser/package.json, packages/misc/package.json, packages/nacl/package.json, packages/pkp-base/package.json, packages/pkp-cosmos/package.json, packages/pkp-ethers/package.json, packages/pkp-sui/package.json, packages/pkp-walletconnect/package.json, packages/types/package.json, packages/uint8arrays/package.json, packages/wasm/package.json, packages/wrapped-keys-lit-actions/package.json, packages/wrapped-keys/package.json
- https://github.com/LIT-Protocol/js-sdk/pull/787
- https://github.com/LIT-Protocol/js-sdk/pull/766
- https://github.com/LIT-Protocol/js-sdk/pull/759
- https://github.com/LIT-Protocol/js-sdk/pull/761
- https://github.com/LIT-Protocol/js-sdk/pull/754
=> Publish version 7.0.5

lerna.json, packages/access-control-conditions/package.json, packages/auth-browser/package.json, packages/auth-helpers/package.json, packages/constants/package.json, packages/constants/src/lib/version.ts, packages/contracts-sdk/package.json, packages/core/package.json, packages/crypto/package.json, packages/encryption/package.json, packages/event-listener/package.json, packages/lit-auth-client/package.json, packages/lit-node-client-nodejs/package.json, packages/lit-node-client/package.json, packages/logger/package.json, packages/misc-browser/package.json, packages/misc/package.json, packages/nacl/package.json, packages/pkp-base/package.json, packages/pkp-cosmos/package.json, packages/pkp-ethers/package.json, packages/pkp-sui/package.json, packages/pkp-walletconnect/package.json, packages/types/package.json, packages/uint8arrays/package.json, packages/wasm/package.json, packages/wrapped-keys-lit-actions/package.json, packages/wrapped-keys/package.json
- https://github.com/LIT-Protocol/js-sdk/pull/793
=> chore: bump to 7.0.6

package.json, packages/constants/src/lib/constants/constants.ts, yarn.lock
Block by merging of: https://github.com/LIT-Protocol/accs-schemas/pull/30
=> Add Moksha network

lerna.json, packages/access-control-conditions/package.json, packages/auth-browser/package.json, packages/auth-helpers/package.json, packages/constants/package.json, packages/constants/src/lib/version.ts, packages/contracts-sdk/package.json, packages/core/package.json, packages/crypto/package.json, packages/encryption/package.json, packages/event-listener/package.json, packages/lit-auth-client/package.json, packages/lit-node-client-nodejs/package.json, packages/lit-node-client/package.json, packages/logger/package.json, packages/misc-browser/package.json, packages/misc/package.json, packages/nacl/package.json, packages/pkp-base/package.json, packages/pkp-cosmos/package.json, packages/pkp-ethers/package.json, packages/pkp-sui/package.json, packages/pkp-walletconnect/package.json, packages/types/package.json, packages/uint8arrays/package.json, packages/wasm/package.json, packages/wrapped-keys-lit-actions/package.json, packages/wrapped-keys/package.json
- https://github.com/LIT-Protocol/js-sdk/pull/713
- https://github.com/LIT-Protocol/js-sdk/pull/803
- https://github.com/LIT-Protocol/js-sdk/pull/772
=> Publish version 7.0.7

lerna.json, packages/access-control-conditions/package.json, packages/auth-browser/package.json, packages/auth-helpers/package.json, packages/constants/package.json, packages/constants/src/lib/version.ts, packages/contracts-sdk/package.json, packages/core/package.json, packages/crypto/package.json, packages/encryption/package.json, packages/event-listener/package.json, packages/lit-auth-client/package.json, packages/lit-node-client-nodejs/package.json, packages/lit-node-client/package.json, packages/logger/package.json, packages/misc-browser/package.json, packages/misc/package.json, packages/nacl/package.json, packages/pkp-base/package.json, packages/pkp-cosmos/package.json, packages/pkp-ethers/package.json, packages/pkp-sui/package.json, packages/pkp-walletconnect/package.json, packages/types/package.json, packages/uint8arrays/package.json, packages/wasm/package.json, packages/wrapped-keys-lit-actions/package.json, packages/wrapped-keys/package.json
=> Publish version 7.0.8

lerna.json, packages/access-control-conditions/package.json, packages/auth-browser/package.json, packages/auth-helpers/package.json, packages/constants/package.json, packages/constants/src/lib/version.ts, packages/contracts-sdk/package.json, packages/core/package.json, packages/crypto/package.json, packages/encryption/package.json, packages/event-listener/package.json, packages/lit-auth-client/package.json, packages/lit-node-client-nodejs/package.json, packages/lit-node-client/package.json, packages/logger/package.json, packages/misc-browser/package.json, packages/misc/package.json, packages/nacl/package.json, packages/pkp-base/package.json, packages/pkp-cosmos/package.json, packages/pkp-ethers/package.json, packages/pkp-sui/package.json, packages/pkp-walletconnect/package.json, packages/types/package.json, packages/uint8arrays/package.json, packages/wasm/package.json, packages/wrapped-keys-lit-actions/package.json, packages/wrapped-keys/package.json
- https://github.com/LIT-Protocol/js-sdk/pull/710
=> Publish version 7.1.0

lerna.json, packages/access-control-conditions/package.json, packages/auth-browser/package.json, packages/auth-helpers/package.json, packages/constants/package.json, packages/constants/src/lib/version.ts, packages/contracts-sdk/package.json, packages/core/package.json, packages/crypto/package.json, packages/encryption/package.json, packages/event-listener/package.json, packages/lit-auth-client/package.json, packages/lit-node-client-nodejs/package.json, packages/lit-node-client/package.json, packages/logger/package.json, packages/misc-browser/package.json, packages/misc/package.json, packages/nacl/package.json, packages/pkp-base/package.json, packages/pkp-cosmos/package.json, packages/pkp-ethers/package.json, packages/pkp-sui/package.json, packages/pkp-walletconnect/package.json, packages/types/package.json, packages/uint8arrays/package.json, packages/wasm/package.json, packages/wrapped-keys-lit-actions/package.json, packages/wrapped-keys/package.json
=> chore: bump version to 7.1.2

lerna.json, packages/access-control-conditions/package.json, packages/auth-browser/package.json, packages/auth-helpers/package.json, packages/constants/package.json, packages/constants/src/lib/version.ts, packages/contracts-sdk/package.json, packages/core/package.json, packages/crypto/package.json, packages/encryption/package.json, packages/event-listener/package.json, packages/lit-auth-client/package.json, packages/lit-node-client-nodejs/package.json, packages/lit-node-client/package.json, packages/logger/package.json, packages/misc-browser/package.json, packages/misc/package.json, packages/nacl/package.json, packages/pkp-base/package.json, packages/pkp-cosmos/package.json, packages/pkp-ethers/package.json, packages/pkp-sui/package.json, packages/pkp-walletconnect/package.json, packages/types/package.json, packages/uint8arrays/package.json, packages/wasm/package.json, packages/wrapped-keys-lit-actions/package.json, packages/wrapped-keys/package.json
- https://github.com/LIT-Protocol/js-sdk/pull/831
=> Publish version 7.2.0

lerna.json, package.json, packages/access-control-conditions/package.json, packages/auth-browser/package.json, packages/auth-helpers/package.json, packages/constants/package.json, packages/constants/src/lib/version.ts, packages/contracts-sdk/package.json, packages/core/package.json, packages/crypto/package.json, packages/encryption/package.json, packages/event-listener/package.json, packages/lit-auth-client/package.json, packages/lit-node-client-nodejs/package.json, packages/lit-node-client/package.json, packages/logger/package.json, packages/misc-browser/package.json, packages/misc/package.json, packages/nacl/package.json, packages/pkp-base/package.json, packages/pkp-cosmos/package.json, packages/pkp-ethers/package.json, packages/pkp-sui/package.json, packages/pkp-walletconnect/package.json, packages/types/package.json, packages/uint8arrays/package.json, packages/wasm/package.json, packages/wrapped-keys-lit-actions/package.json, packages/wrapped-keys/package.json, yarn.lock
- https://github.com/LIT-Protocol/js-sdk/pull/835
=> chore: bump version to 7.2.1 and update dependencies

README.md
=> doc(README): initialise new README

lerna.json, packages/access-control-conditions/package.json, packages/auth-browser/package.json, packages/auth-helpers/package.json, packages/constants/package.json, packages/constants/src/lib/version.ts, packages/contracts-sdk/package.json, packages/core/package.json, packages/crypto/package.json, packages/encryption/package.json, packages/event-listener/package.json, packages/lit-auth-client/package.json, packages/lit-node-client-nodejs/package.json, packages/lit-node-client/package.json, packages/logger/package.json, packages/misc-browser/package.json, packages/misc/package.json, packages/nacl/package.json, packages/pkp-base/package.json, packages/pkp-cosmos/package.json, packages/pkp-ethers/package.json, packages/pkp-sui/package.json, packages/pkp-walletconnect/package.json, packages/types/package.json, packages/uint8arrays/package.json, packages/wasm/package.json, packages/wrapped-keys-lit-actions/package.json, packages/wrapped-keys/package.json
- https://github.com/LIT-Protocol/js-sdk/pull/905
=> chore: bump version to 7.3.1 across all packages

packages/constants/src/lib/constants/constants.ts
=> 0gMainnet https RPC

.github/workflows/health-checks.yml
Change health check from 30 minutes to 5 minutes
=> chore: update health check schedule to run every 5 minutes
