LIT-Protocol/js-sdk

- package.json
- yarn.lock
Updated the lit-connect-modal versions in the root package.json to include Coinbase Wallet in the modal.
A team requested this feature.
Simple package & yarn.lock update
Haven't updated the apps. They still have the old versions of the Modal
> feat: Update Lit Connect Modal to include Coinbase wallet

- lerna.json
- packages/access-control-conditions/package.json
- packages/auth-browser/package.json
- packages/bls-sdk/package.json
- packages/constants/package.json
- packages/contracts-sdk/package.json
- packages/crypto/package.json
- packages/ecdsa-sdk/package.json
- packages/encryption/package.json
- packages/lit-node-client/package.json
- packages/lit-third-party-libs/package.json
- packages/misc-browser/package.json
- packages/misc/package.json
- packages/nacl/package.json
- packages/uint8arrays/package.json
We want to Repository and homepage links on the npm package page
Add the following to each of the package.json
```
"homepage": "https://github.com/Lit-Protocol/js-sdk",
"repository": {
"type": "git",
"url": "https://github.com/LIT-Protocol/js-sdk"
},
```
> feat: add npm registry metadata

- packages/lit-node-client/src/lib/lit-node-client.ts
- packages/types/src/lib/interfaces.ts
- Added several functions that finishes the WebAuthn authentication flow by sending a credential assertion to the Lit Nodes and asking them to generate signature shares for signing an **AuthSig** (not **SessionSig**) with the PKP tied to the WebAuthn credential. The shares are then recombined in the SDK into a valid signature. 
- Manually tested and it works.
> Implement generating authSig from nodes for WebAuthn authentication flow

- packages/lit-node-client-nodejs/src/lib/lit-node-client-nodejs.ts
We changed node code to return with authSig key instead.
> Destructure with authSig instead of sessionSig

- .prettierrc
- packages/encryption/src/lib/params-validators.ts
- packages/lit-node-client-nodejs/src/lib/lit-node-client-nodejs.ts
- packages/types/src/lib/interfaces.ts
remove parser: babel from .prettierrc so it works with typescript.  add functionality to send AuthMethods with executeJS request
> Add AuthMethods to executeJs params so that it matches what we have in lit-js-sdk

- packages/lit-node-client-nodejs/src/lib/lit-node-client-nodejs.ts
- packages/types/src/lib/interfaces.ts
to avoid this error when running from nodejs server: 
```
TypeError: Cannot read properties of undefined (reading 'host')
at LitNodeClientNodeJs.signSessionKey (/Users/saike/Code/null.world/null-network-backend/node_modules/@lit-protocol/lit-node-client-nodejs/src/lib/lit-node-client-nodejs.js:1609:45)
at Object.authNeededCallback (file:///Users/saike/Code/null.world/null-network-backend/utils/lit.js:199:46)
at LitNodeClientNodeJs.getSessionSigs (/Users/saike/Code/null.world/null-network-backend/node_modules/@lit-protocol/lit-node-client-nodejs/src/lib/lit-node-client-nodejs.js:1784:46)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Lit.getSessionSig (file:///Users/saike/Code/null.world/null-network-backend/utils/lit.js:211:18)
at async …
```
>  globalThis.location.host nodejs fix

- apps/html/manual_tests.html
- apps/html/manual_tests_error_messages.html
- apps/html/manual_tests_session_keys.html
- apps/html/manual_tests_unified.html
- cypress/e2e/spec.cy.ts
- packages/access-control-conditions/src/lib/canonicalFormatter.spec.ts
- packages/access-control-conditions/src/lib/canonicalFormatter.ts
- packages/access-control-conditions/src/lib/hashing.ts
- packages/access-control-conditions/src/lib/humanizer.ts
- packages/auth-browser/src/lib/auth-browser.ts
- packages/auth-browser/src/lib/chains/cosmos.ts
- packages/auth-browser/src/lib/chains/eth.ts
- packages/auth-browser/src/lib/chains/sol.ts
- packages/constants/src/lib/errors.ts
- packages/crypto/src/lib/crypto.ts
- packages/encryption/src/lib/encryption.ts
- packages/encryption/src/lib/params-validators.ts
- packages/lit-node-client-nodejs/src/lib/lit-node-client-nodejs.ts
- packages/misc-browser/src/lib/misc-browser.ts
- packages/misc/src/lib/misc.spec.ts
- packages/misc/src/lib/misc.ts
- packages/types/src/lib/interfaces.ts
Closes LIT-191. See issue for more details.
- This PR makes it so that old error codes (`storage_error`, `not_authorized`) from the node, as well as errors thrown from within the SDK (unrelated to node API calls) **are all unified into the new style of PascalCase codes, as well as the ability to parse new error response fields such as `errorKind`, `status` etc.**
- If nodes return `errorCode: 'storage_error'`, SDK returns `errorCode: 'NodeStorageError'`
- If nodes return `errorCode: 'NodeStorageError'`, SDK returns the same.
Run `yarn build:packages`, then `yarn tools --dev --apps` to spin up `http://localhost:4002` which you can use for manual testing.
Manually tested using `http://localhost:4002/manual_tests.html` as an example, and the `Encrypt, set the conditions, then try to update …
> Handle New / Old SDK Errors

- packages/auth-browser/src/lib/auth-browser.ts
- packages/auth-browser/src/lib/chains/cosmos.ts
- packages/types/src/lib/interfaces.ts
This PR replaces the previously hardcoded window.keplr with multiple wallet options for Cosmos (Keplr/Leap/Cypher) when using `checkAndSignAuthMessage`.
It does not interfere with the functionality of any other chain option except the Cosmos chains. It also defaults to Keplr when a specific wallet is not specified, meaning no changes to current implementation would be necessary.
Note: No `cypher` option is present as Cypher Wallet uses the `window.keplr` object.
> Add support for Leap & Cypher wallets for Cosmos

- packages/auth-browser/src/lib/chains/sol.ts
- fixes bug with Solana auth signature generation throwing an exception `provider.connect is not as function`
- The provider resolver would check for the `keplr and solana` on the global window. checking keplr first and falling back to Solana. However, `keplr` does not have `connect` on its api screen show below showing the difference in the two api's 
- We now only check for `solana` on the global window which does correctly sign with solana wallets
- tested using phantom wallet with `lit-node-client` can correctly generate auth signatures and store in local storage
> fix to solana auth signature generation

- tools/scripts/map-deps-to-dist.mjs
This PR **adds** `peerDependencies` to `dependencies` regardless if any imports / dependencies have been detected. 
Sometimes we may want to specify a peerDependency for a library that does not even get imported - for example, `auth-helpers` specify `tslib` peer dependency but there is no explicit import for that in code that is detected by us.
> Add peerDependencies to dependencies regardless if any imports detected

- packages/lit-auth-client/src/index.ts
- packages/lit-auth-client/src/lib/lit-auth-client.spec.ts
- packages/lit-auth-client/src/lib/providers/OtpProvider.ts
- packages/types/src/lib/interfaces.ts
**Summary**
- Export `OtpProvider` from `lit-auth-client`
- Made properties in `OtpProviderOptions` type optional
- Update port to `443`
**Tests**
Tested in React TS.
> fix: export OtpProvider

- README.md
- tools/scripts/gen-readme.mjs
- The package tables have been restructured into two distinct sections. The first section highlights our primary entry points, `lit-node-client` and `lit-node-client-nodejs`. The second part is tailored for technically adept users, listing additional modules that they may find useful. (see [here](https://github.com/LIT-Protocol/js-sdk/tree/feature/lit-767-js-sdk-update-docs-to-hidetoggle-all-other-available#packages)) 
- Added a new `Quick Start` guide in the Contributing section offering straightforward steps to getting started (see [here](https://github.com/LIT-Protocol/js-sdk/tree/feature/lit-767-js-sdk-update-docs-to-hidetoggle-all-other-available#contributing-and-developing-to-this-sdk))
For anyone who's interested, [here](https://github.com/LIT-Protocol/js-sdk/blob/a53ec30fe1a80f4104 …
> docs: clearer instructions

- packages/auth-browser/src/lib/chains/eth.ts
- packages/lit-auth-client/src/lib/providers/BaseProvider.ts
- packages/lit-node-client-nodejs/src/lib/lit-node-client-nodejs.ts
**Summary**
- Use custom session key in lit-auth-client `getSessionSigs`
- Clear `WALLET_SIGNATURE` in `disconnectWeb3`
- Call out `disconnectWeb3` in comments
Tested in browser and node envs.
> fix: pass custom session key, clear wallet sig

- packages/types/src/lib/interfaces.ts
- Adds required cheqd-specific explicit propertieson ACC types.
- Utilises `parameters` as `string[]`, rather than generic `params` as `any[]`. Details are implementation specific.
- Brings `method` as optional at ACC definition layer for consistency.
Implementation Reference: https://github.com/LIT-Protocol/lit-assets/pull/244 .
> Add/cheqd-specific cosmos ACC properties

- packages/pkp-base/src/lib/pkp-base.ts
- packages/types/src/lib/interfaces.ts
- Adds ability for the `pkp-base` to allow for configuring custom network options for the underlying `LitNodeClient` instance
> add custom network options

- packages/auth-browser/src/lib/chains/sol.ts
The [Backpack wallet 🎒](https://www.backpack.app/) extension does not inject a `solana` object into the window, so at this moment, it's incompatible with Lit Protocol.
This checks for the presence of the `backpack` object into the window to support backpack users.
Here's the signature of the `window.solana` object using the Phantom wallet:
```ts
isConnected: boolean;
isPhantom: boolean;
publicKey: PublicKey | null;
```
Here's the signature of the `window.backpack` object using the Backpack wallet:
```ts
connection: Connection;
isBackpack: boolean;
isConnected: boolean;
isXnft: boolean;
publicKey: PublicKey | null;
```
> Add Backpack wallet support

- packages/lit-auth-client/src/lib/providers/BaseProvider.ts
This PR:
- Fixes SDK bug where the SIWE statement is malformed, thus causing server-side verification of the SIWE message to fail.
> Pass in statement from authCallbackParams to signSessionKey

- apps/demo-lit-connect-modal-next/README.md
- apps/demo-lit-connect-modal-next/package-lock.json
- apps/demo-lit-connect-modal-next/package.json
**Summary**
Use new packages in `demo-lit-connect-modal` app
> chore: update pkgs in demo-lit-connect-modal

- packages/crypto/polyfills.js
- packages/crypto/src/lib/crypto.spec.ts
- packages/crypto/src/lib/crypto.ts
fixes an observed issue with `encryptWithSymmetricKey` which throws an error in NodeJS when attempting to use the `Blob` object as it is not available in global scope. 
refactors to check for if the env is `node` and then imports `node:buffer` to use the compatible `Blob` object
> add check for node runtime and import from node buffer for Blob

- packages/contracts-sdk/src/lib/contracts-sdk.ts
I came into this as a roadblock and not being able to get my claim through. I figure the tx object should still be available in the helper function and should overwrite the cost to mint, but could probably figure out a way to make cost to mint as the default in the object. Either way. Would appreciate a look and a merge.
> make a change to claim and mint to add in tx options

- packages/encryption/src/lib/encryption.ts
- packages/encryption/src/lib/params-validators.ts
`encryptFileAndZipWithMetadata` was not working for the @lit-protocol/lit-node-client-nodejs version of the sdk.
Presumably the `zipBlob = await zip.generateAsync({ type: 'blob' })` works properly only in browser env.
- The function now returns a `nodebuffer` instead of `blob` when not on browser env.
- The file validation function now accepts a 'Uint8array' and not only the client side 'Blob','File' obj
Node v18.16, tested both on next.js and standalone script
> fix encryptFileAndZipWithMetadata node

- packages/nacl/src/lib/nacl.ts
A hack was added a year ago to suppress a webpack complaint. Other packages import crypto and don't seem to contain this hack. The metro bundler doesn't allow for conditional requires / substitutions, and as such causes react-native to fail loading the crypto library. This PR removes the hack.
I have not checked if webpack still complains but am hoping Chris can chime in.
> fix(nacl): remove require hack

- apps/html/manual_tests.html
- e2e-nodejs/group-hotwallet-with-blockhash/test-hotwallet-with-blockhash.mjs
- packages/auth-browser/src/lib/auth-browser.ts
- packages/auth-browser/src/lib/chains/eth.ts
- packages/constants/src/lib/errors.ts
- packages/core/src/lib/lit-core.ts
- packages/lit-auth-client/src/lib/providers/EthWalletProvider.ts
- packages/lit-node-client-nodejs/src/lib/lit-node-client-nodejs.ts
- packages/types/src/lib/ILitNodeClient.ts
- packages/types/src/lib/interfaces.ts
Stores `latest_blockhash` returned by the nodes in the handshake to the `litNodeClient` instance. This is used as the nonce when crafting the SIWE message for signing in both `AuthSig` & `SessionSigs`.
This PR is **backwards-compatible** i.e. devs can still choose not to provide the `nonce` in the updated signing functions and I've also taken care of the fact the node currently don't return `latest_blockhash`.
Updated the following functions to accept the nonce which can be fetched from stored in the client using the `getLatestBlockhash()`:
- `checkAndSignAuthMessage`
- `checkAndSignEVMAuthMessage`
- `signAndSaveAuthMessage`
- `_signAndGetAuth`
```
const litNodeClient = new LitJsSdk.LitNodeClient({
litNetwork: "cayenne",
});
await litNodeClient.connect();
const nonce = …
```
> feat: Store blockhash from handshake + use it in SIWE

- packages/contracts-sdk/src/lib/contracts-sdk.ts
- packages/core/src/lib/lit-core.ts
Makes minNodeCount be the count of the set of active nodes
> set minNodeCount to all active nodes

- e2e-nodejs/group-lit-actions/test-lit-action-2-sigs.mjs
- packages/contracts-sdk/src/lib/contracts-sdk.ts
- packages/core/src/lib/lit-core.ts
> connect to all nodes, fix kicked nodes filtering

- packages/lit-node-client-nodejs/src/index.ts
- packages/lit-node-client/src/index.ts
When you're using the Lit SDK in combination with packages that load WASM modules, the global `node-fetch` override breaks local / data-url file imports. We noticed this when running lit along the new [web3.storage SDK](@web3-storage/w3up-client).  Its wasm-bindgen generated code actually loads the binaries using a `data:` url (see https://github.com/web3-storage/fr32-sha2-256-trunc254-padded-binary-tree-multihash/blame/main/gen/wasm.js#L284C32-L284C32) which works fine with any fetch in node and browser environments but that's not supported by node-fetch < version 3.
Here's a project that uses both libraries: https://github.com/elmariachi111/w3up-next-sample. yarn & yarn build this to see the error messages.
-> alternatively we'd suggest to bump your node-fetch version. 
- [o] New …
> only polyfill node's global fetch when it's definitely undefined

- e2e-nodejs/0_manual-tests/test-relayer-mint.mjs
- packages/lit-auth-client/src/lib/lit-auth-client.ts
```
NETWORK=manzano node ./e2e-nodejs/0_manual-tests/test-relayer-mint.mjs
```
> [e2e test] add manzano & habanero relayer test

- packages/types/src/lib/interfaces.ts
- Makes `capacityDelegationAuthSig` optional on `SessionSigsParams` as we do not need to delegate capacity credit as the `authSig` will be used in place of the `capacityDelegationAuthSig` which is a valid use case as developers may either
- Delegate usage through `capacityDelegationAuthSig`
- Provide proof of Capacity Credit through a `authSig`
> make capacityDelegationAuthSig optional

- packages/logger/src/lib/logger.spec.ts
- packages/logger/src/lib/logger.ts
fixes the `logger.spec.ts` tests where two tests where failing after a previous PR refactor to how the logger groups request identifiers when persisting to `Storage`
> Fix logging tests in 3.1.2 staging

- tools/scripts/tools.mjs
We have this small script that checks if all the dependencies are on the same version in the built package.json. However, it was checking any packages starting with `@lit-protocol`. Since `@lit-protocol/accs-validator` is outside of the monorepo and does not share the same version, I'm adding it to the `ignoreList`, which was previously created to handle such cases.
```
yarn node ./tools/scripts/tools.mjs --verify      
```
- https://github.com/LIT-Protocol/js-sdk/pull/320#pullrequestreview-1868693437
> fix: add accs-validator to ignoreList

- packages/constants/src/lib/enums.ts
- packages/crypto/src/lib/crypto.spec.ts
- packages/crypto/src/lib/crypto.ts
- packages/lit-node-client-nodejs/src/lib/lit-node-client-nodejs.ts
Add `K256` as alias of `ECDSA_CAIT_SITH` sig type, and mark `ECDSA_CAIT_SITH` legacy.
It was implemented with minimal changes to the code, but it still needs to be tested against the nodes.
> Add `K256` as alias of `ECDSA_CAIT_SITH` sig type

- packages/constants/src/lib/enums.ts
- packages/crypto/src/lib/crypto.spec.ts
- packages/crypto/src/lib/crypto.ts
- packages/lit-node-client-nodejs/src/lib/lit-node-client-nodejs.ts
Just adds a comment for clarity
> add comment pointing to repo

- packages/logger/src/lib/logger.ts
replaces `ethers.utils.hashMessage` with a non secure 32 bit hash function which has a low collision chance but quick throughput. This does mean the hashing function is non secure, meaning it is possible to reverse hashes in reasonable time. However we do need a secure hashing implementation for the purposes of the logger. 
Test times are observed to be the same and in some cases **100 - 200ms faster**  measurement was done with `logger.spec.ts` tests with both hashing implementations. 
`logger.spec.ts` was run against the new hashing function
> ref: Remove ethers in logger

- e2e-nodejs/group-rli/test-rli-from-lit-node-client-no-delegatee.mjs
- package.json
- packages/lit-node-client-nodejs/src/lib/lit-node-client-nodejs.ts
- packages/pkp-client/src/lib/wallet-factory.spec.ts
When creating a delegation authsig, the delegateeAddresses should be optional
```
DEBUG=true NETWORK=manzano MINT_NEW=true yarn test:e2e:nodejs --filter=test-rli-from-lit-node-client-no-delegatee.mjs
```
> Feature/lit 2491 js sdk make delegateeAddresses field optional

- packages/lit-auth-client/src/lib/providers/DiscordProvider.ts
- packages/lit-auth-client/src/lib/providers/GoogleProvider.ts
- packages/lit-auth-client/src/lib/utils.ts
This PR adds a signin method that handles authenticating with an oauth provider using a popup modal instead of a redirect and two steps
This feature requires [lit-login-server PR#4](https://github.com/LIT-Protocol/lit-login-server/pull/4)
> Enable signin using popup modals instead of redirections

- packages/contracts-sdk/src/lib/utils.ts
This PR addresses an issue in the `calculateUTCMidnightExpiration` function, where calculations for expiration timestamps were inaccurately computed for users in timezones ahead of UTC. Specifically, when attempting to calculate the expiration timestamp with a parameter like `daysUntilUTCMidnightExpiration: 1`, the result would inaccurately represent less than 24 hours until expiration due to the discrepancy between local and UTC times.
minting rli with 1 day expiration
> fix: calculation should be UTC now instead of executor's now

- .eslintrc.json
- README.md
- e2e-nodejs/0_manual-tests/test-epoch-cache.mjs
- lerna.json
- package.json
- packages/constants/src/lib/constants/constants.ts
- packages/constants/src/lib/version.ts
- packages/core/src/lib/lit-core.ts
- packages/types/src/lib/interfaces.ts
- yarn.lock
- https://github.com/LIT-Protocol/js-sdk/pull/398
> [Release] 4.0.0

- packages/lit-node-client-nodejs/src/lib/lit-node-client-nodejs.ts
Modifies logic in `createCapacityDelegationAuthSig()` so that callers can omit the `delegateeAddresses` and the behaviour will be that _anyone_ can use it rather than the current logic which adds an empty array,  making it so _nobody_ can use it :)
**Without** this fix, we actually created and set an empty array into the `delegate_to` property on the capability, which meant "Nobody can use this".
**With** this fix, we don't set `delegate_to` on the capability at all if no `delegateeAddresses` was provided as an argument.  This means "Anyone can use this".  It matches the behaviour [described in our docs](https://github.com/LIT-Protocol/docs/blob/9f6bccaad533bafa34b9e4020feca6b74186c57b/docs/sdk/capacity-credits.md?plain=1#L88).
- I ran `eslint -- fix` on the file, so there are incidental …
> LIT-2658 - Empty delegateeAddresses passed to createCapacityDelegationAuthSig() now means "everyone can use this"

- packages/core/src/lib/lit-core.ts
- packages/types/src/lib/interfaces.ts
After we removed the any union type on the node client constructor in v4.1, users began reporting that they were being forced to add properties to the configuration that they did not expect to be required.
Upon inspection, there is a complete set of default values for the node client provided in lit-core , some properties are set in the code itself based on the value of litNetwork, and others are loaded from the on-chain staking contract.
Thus, every property in the config is theoretically optional except for litNetwork — but this was being hidden by the any union type that was allowing consumers to pass objects with any shape into the constructor.
This PR makes those properties optional.
Please describe the tests that you ran to verify your changes. Provide instructions so we can …
> fix(types): LIT-2706 - Modify LitNodeClientConfig properties incorrectly marked as required to be optional

- packages/lit-auth-client/src/lib/providers/GoogleProvider.ts
This PR changes the AuthMethodType returned when signing in with google using a popup to GoogleJwt, which is the one used when creating domain wallets pkps and therefore the one used in the wagmi connector
> fix: use AuthMethodType.GoogleJwt when loging in using popup

- packages/auth-browser/src/lib/chains/eth.ts
Fixes #416 where `global` was used over `globalThis`
> fix: global buffer polyfiil

- packages/lit-node-client-nodejs/src/lib/lit-node-client-nodejs.ts
When creating session sigs, user will need to prefix their pkp public key with hex `0x`, and if they don't, they will run into
```
error: invalid arrayify value (argument="value", value="048161e8dd7b3efc0c1dab3c6e89d3c3f0181947d4a35994113b32f30a86f3f4bc0cdc4d3ea12c6afa42252dfc3a8316b298d78aa6470da59d260432d644bba84a", code=INVALID_ARGUMENT, version=bytes/5.7.0)
```
when trying to sign. We should really just prefix it for them if it's not already.
Before
```ts
const sessionSigs = await litNodeClient.getSessionSigs({
pkpPublicKey: `0x${pkpPublicKey}`;
expiration: expiration,
chain: 'ethereum',
resourceAbilityRequests: [
{
resource: new LitPKPResource('*'),
ability: LitAbility.PKPSigning,
},
],
```
After
```ts
const sessionSigs = await litNodeClient.getSessionSigs({
pkpPublicKey: …
```
> feat(lit-node-client-nodejs): prefix 0x to pkp pubkey if not present

- e2e-nodejs/group-pkp-auth-method/test-pkp-eth-wallet-provider.mjs
- packages/lit-auth-client/src/lib/providers/EthWalletProvider.ts
- packages/types/src/lib/interfaces.ts
At the moment, if you want to create an eth wallet auth method from Lit Auth Client, you will need to provide an API key. This shouldn't be the case because it's all client side signing the siwe message, and all we do is wrap around their authSig as an access token as an auth method. 
Create a static `authenticate` method, and then the original method can consume the static method, so that it can still use the base methods that relies on the relayer 
```ts
const authMethod = await EthWalletProvider.authenticate({
signer: wallet,
litNodeClient: client,
});
```
```
DEBUG=true NETWORK=cayenne yarn test:e2e:nodejs --filter=test-pkp-eth-wallet-provider.mjs
```
```
✓    authMethod created: {"authMethodType":1,"accessToken":"{\"sig\":\"0x433c7c22d488dc604b610312c2ad074d1c3e339d42fb14a80430fee6963 …
```
> feat: decouple eth wallet from provider

- lit.config.json
- packages/crypto/src/lib/crypto.ts
AMD certificate endpoints are rate limited, so we are going to always use our Lit CORS server caches certificates locally to avoid hitting the rate limit.
```
DEBUG=true yarn test:e2e:node --filter=multi-network          
```
> feat(AMD Cert): Always fetch from CORS

- packages/types/src/lib/interfaces.ts
TypeScript displays `/** ... */` comments on properties but ignores `// ...` comments. This PR fixes comment docs for a single interface (the one I'm currently dealing with).
Also added an example for the `expiration` field.
> Fix doc strings for GetSessionSigsProps

- e2e-nodejs/group-connection/test-connection-cert-caching.mjs
- packages/crypto/src/lib/crypto.ts
Changes a conditional check for storing AMD SEV SNP certificates in `localstorage` to now check if the api is available rather than doing a check for a browser environment. this will allow for caching in local storage in non browser environments if the api is available. 
A new `connection` e2e test has been added which defines a `localstorage` provider and checks that certs have been cached after `connect` finishes.
> feat: allow cert caching if local storage is defined

- packages/constants/src/lib/constants/constants.ts
Add `lit`(Chronicle) to the [supported chains](https://developer.litprotocol.com/v3/resources/supported-chains) page.
Adding to docs is done automatically using script. But it appears `lit` as an supported chain is missing from [constants.ts](https://github.com/LIT-Protocol/js-sdk/blob/068a0f4dd9a6705105c1bab81c20931cfd597ed1/packages/constants/src/lib/constants/constants.ts#L35)
As @glitch003 suggested, let's add a new chain in constants.ts with the name `lit`, with the same exact data as the `chronicleTestnet` entry. Then, once the new SDK is published, any commit to the docs repo will automatically pull down the latest version of the SDK and regenerate the list of supported chains in the doc (it's a pre-commit hook in the docs repo).
Please describe the tests that you ran to verify …
> add(chain): add 'lit' to supported chains in constant.ts file

- packages/lit-auth-client/src/lib/providers/BaseProvider.ts
- packages/types/src/lib/interfaces.ts
New Implementation suggested here:
https://github.com/LIT-Protocol/js-sdk/pull/443#issuecomment-2079735472
> Feature/lit 3041 js sdk cherry pick fixes for session key mismatch 443#issuecomment 2082614246

- packages/lit-node-client-nodejs/src/lib/lit-node-client-nodejs.spec.ts
- packages/lit-node-client-nodejs/src/lib/lit-node-client-nodejs.ts
Adds an undefined check for using the `in` syntax for property check against `args` instance.
> fix: Remove invalid test case and adds an exception if no `arguments` are supplied to `LitNodeClient`

- packages/lit-node-client-nodejs/src/lib/lit-node-client-nodejs.ts
Fixes an issue with session key signatures having an expiration of 5 minutes regardless of what was set by the user as an `expiration`
> fix: session key signature default expiration always used

- .github/workflows/ci.yml
- local-tests/test.ts
- local-tests/tests/testExecuteJsBroadcastAndCollect.ts
- local-tests/tests/testExecuteJsDecryptAndCombine.ts
- local-tests/tests/testExecuteJsSignAndCombineEcdsa.ts
Adds  Lit Action API test cases for `signAndCombineEcdsa`, `decryptAndCombine` and `broadcastAndCollect`
> test(la-sign-combine): add test cases

- local-tests/setup/tinny-environment.ts
- packages/contracts-sdk/src/lib/contracts-sdk.ts
- packages/core/src/lib/lit-core.ts
- packages/pkp-base/src/lib/pkp-base.ts
- packages/types/src/lib/interfaces.ts
- Solution leverages the existing `contractContext`functionality to maintain backwards compatibility with consumers who use that API
- Fixed `config.rpcUrl` being optional string, but also a union with `null` -- this conflicted with the definition of same in the contract SDK and it made no sense to default an optional parameter to `null` anyway 🤦  :)
- Moved verification of the `litNetwork` to the constructor rather than it being nestled inside of `setConfig()` where it would explode the first time someone actually connected with the client after configuring it with an invalid network
- Removed `setNewConfig`, which was an internal method that would leave the core / client in an inconsistent state if ever called outside of the `connect()` flow.
- Standardized initialization so that we no …
> LIT-3394 - Improve connect() performance

- packages/core/src/lib/lit-core.ts
Fixes a small bug from pr #502 where we would not respect the `contractResolver` address if provided which breaks some local development flows.
> fix(core): contract context

- packages/lit-node-client-nodejs/src/lib/helpers/validate-bls-session-sig.ts
- packages/lit-node-client-nodejs/src/lib/lit-node-client-nodejs.ts
A user found a bug where the SDK was sending an expired BLS session sig.  I discovered that we aren't checking the expiration when we are checking if we need to resign the session key.  We do this check for ECDSA, because it's built into SIWE, but we can't use SIWE verification for the BLS session sig, because SIWE doesn't understand BLS.  
So we're checking the sig already, and this PR just copy/pastes the timestamp verification code from the SIWE repo here: https://github.com/spruceid/siwe/blob/main/packages/siwe/lib/client.ts#L289
This makes it so that we check the expiration and issued at time, and then throw an error if they're not valid.  The calling function (`checkNeedToResignSessionKey()`) catches errors and will try to re-sign if the SIWE is expired.
> check timestamps of BLS session sigs

- lerna.json
- packages/access-control-conditions/package.json
- packages/auth-browser/package.json
- packages/auth-helpers/package.json
- packages/bls-sdk/package.json
- packages/constants/package.json
- packages/constants/src/lib/version.ts
- packages/contracts-sdk/package.json
- packages/core/package.json
- packages/crypto/package.json
- packages/ecdsa-sdk/package.json
- packages/encryption/package.json
- packages/lit-auth-client/package.json
- packages/lit-node-client-nodejs/package.json
- packages/lit-node-client/package.json
- packages/logger/package.json
- packages/misc-browser/package.json
- packages/misc/package.json
- packages/nacl/package.json
- packages/pkp-base/package.json
- packages/pkp-client/package.json
- packages/pkp-cosmos/package.json
- packages/pkp-ethers/package.json
- packages/pkp-sui/package.json
- packages/pkp-walletconnect/package.json
- packages/sev-snp-utils-sdk/package.json
- packages/types/package.json
- packages/uint8arrays/package.json
- packages/wrapped-keys/package.json
- #515 has been merged, which was the last blocker for publishing v6.1.0
- This PR bumps NPM package versions to 6.1.0 for all packages as a final step pre-publish.
> Bump versions to v6.1.0 pre-publish to NPM

- packages/pkp-ethers/src/lib/pkp-ethers.ts
This is a quick patch for 6.1.1 - Proper fix is handled in this PR https://github.com/LIT-Protocol/js-sdk/pull/523
> fix: wrong rpc in pkp ethers

- local-tests/tests/wrapped-keys/testExportWrappedKey.ts
- local-tests/tests/wrapped-keys/testGenerateEthereumWrappedKey.ts
- local-tests/tests/wrapped-keys/testGenerateSolanaWrappedKey.ts
- packages/wrapped-keys/esbuild.config.js
- packages/wrapped-keys/src/lib/api/export-private-key.ts
- packages/wrapped-keys/src/lib/lit-actions-client/constants.ts
- packages/wrapped-keys/src/lib/lit-actions-client/export-private-key.ts
- packages/wrapped-keys/src/lib/lit-actions-client/index.ts
- packages/wrapped-keys/src/lib/lit-actions-client/types.ts
- packages/wrapped-keys/src/lib/litActions/common/src/exportPrivateKey.js
- packages/wrapped-keys/src/lib/litActions/ethereum/src/signMessageWithEthereumEncryptedKey.js
- packages/wrapped-keys/src/lib/litActions/ethereum/src/signTransactionWithEthereumEncryptedKey.js
- packages/wrapped-keys/src/lib/litActions/solana/src/signMessageWithSolanaEncryptedKey.js
- packages/wrapped-keys/src/lib/litActions/solana/src/signTransactionWithSolanaEncryptedKey.js
- packages/wrapped-keys/src/lib/litActions/utils.js
- packages/wrapped-keys/src/lib/types.ts
Currently Wrapped Keys export feature simply decrypts the private key on the client. This PR updates the export to happen via a Lit Action and returns the decrypted key from inside the Lit Action. Exporting through a Lit Action also allows us to add more restrictions on the export feature like allow decryption only inside certain permitted Lit Actions which is not currently the case.
Also fixed the following:
1. `signMessageWithEthereumEncryptedKey` Lit Action was **not** initializing the Ethers wallet with the decrypted private key. This was accidentally left out in this commit: https://github.com/LIT-Protocol/js-sdk/pull/515/commits/2fbd86136198fc194133f805ccdd51feb4345a6f#diff-cfa4907cf70adeff456099de1858fb36fb1d13060b43e6357f6c932c679f815fL41
2. All the Lit Actions are using …
> Feat: Update Wrapped keys Export to use Lit Actions

- local-tests/setup/shiva-client.ts
- local-tests/setup/tinny-person.ts
- packages/contracts-sdk/src/lib/addresses.ts
- packages/contracts-sdk/src/lib/contracts-sdk.spec.ts
- packages/contracts-sdk/src/lib/contracts-sdk.ts
- packages/core/src/lib/lit-core.ts
- packages/pkp-ethers/src/lib/pkp-ethers.ts
Reference issue - https://github.com/ethers-io/ethers.js/issues/901 Cuts our RPC request time costs approximately in half by eliminating a sequential call to get `chainId` from every(!) contract call we make
Replaced ethers JSONRPCProvider instances with StaticJSONRPCProvider
This eliminates unnecessary RPC calls to get `chainId` every time we use one of our contract methods.
> fix: LIT-3607 - Use StaticJsonRpcProvider to improve performance of RPC requests

- .github/workflows/ci.yml
- packages/constants/src/lib/constants/constants.ts
- packages/contracts-sdk/src/lib/contracts-sdk.ts
- packages/core/src/lib/lit-core.ts
- Introducing `nodeProtocol` to customise the HTTP protocol for node connections
- Added a check to determine if port is 443, if so use HTTPS
> feat: add custom `nodeProtocol` and enable `https` for port `443`

- packages/constants/src/lib/constants/mappers.ts
Add  `GENERAL_WORKER_URL_BY_NETWORK` constant back so it's not a breaking change.
> feat: add deprecated notice for `GENERAL_WORKER_URL_BY_NETWORK` constant

- lerna.json
- packages/access-control-conditions/package.json
- packages/auth-browser/package.json
- packages/auth-helpers/package.json
- packages/bls-sdk/package.json
- packages/constants/package.json
- packages/constants/src/lib/version.ts
- packages/contracts-sdk/package.json
- packages/core/package.json
- packages/crypto/package.json
- packages/ecdsa-sdk/package.json
- packages/encryption/package.json
- packages/lit-auth-client/package.json
- packages/lit-node-client-nodejs/package.json
- packages/lit-node-client/package.json
- packages/logger/package.json
- packages/misc-browser/package.json
- packages/misc/package.json
- packages/nacl/package.json
- packages/pkp-base/package.json
- packages/pkp-client/package.json
- packages/pkp-cosmos/package.json
- packages/pkp-ethers/package.json
- packages/pkp-sui/package.json
- packages/pkp-walletconnect/package.json
- packages/sev-snp-utils-sdk/package.json
- packages/types/package.json
- packages/uint8arrays/package.json
- packages/wrapped-keys/package.json
[6.2.3] - 2024-07-24
- Remove internal use of `GENERAL_WORKER_URL_BY_NETWORK` and use `NETWORK_CONTEXT_BY_NETWORK` from `@lit-protocol/contracts` from https://github.com/LIT-Protocol/lit-contracts/ instead
- Add custom `nodeProtocol` and enable `https` for port `443`
- *(tools)* Add `@lit-protocol/contracts` to ignore list when validating dependencies version
- *(lit-core)* Should use `RPC_URL_BY_NETWORK` for default config
- *(ci)* Make CI run whole test suite
- *(ci)* Increase chunk size to `9`
- *(comment)* Https://github.com/LIT-Protocol/js-sdk/pull/554#discussion_r1689609337
- *(constants)* Added deprecated notice for `GENERAL_WORKER_URL_BY_NETWORK` constant
> Publish version 6.2.3

- packages/lit-node-client-nodejs/src/lib/helpers/validate-bls-session-sig.ts
when testing this myself, issuedAt is set, and notBefore is never set.  so I think we should use issuedAt.  i see the error below this change ("Invalid SIWE message. Missing expirationTime or issuedAt.") printing when using the latest SDK to sign a session sig for a PKP.
From a repl test:
```
➜  js-sdk git:(master) node
Welcome to Node.js v20.14.0.
Type ".help" for more information.
> const a = `litprotocol.com wants you to sign in with your Ethereum account:
... 0x445c022E61137a2f60E42eCeaE1461bd0F3EEA0a
... 
... Lit Protocol PKP session signature I further authorize the stated URI to perform the following actions on my behalf: I further authorize the stated URI to perform the following actions on my behalf: (1) 'Threshold': 'Execution' for 'lit-litaction://*'. (2) 'Threshold': 'Signing' …
```
> use issued at instead of notBefore

- local-tests/setup/tinny-environment.ts
- local-tests/setup/tinny-utils.ts
- packages/core/src/lib/lit-core.ts
This PR essentially says:
if now < epoch start time + 30s, use `epoch number - 1`.  
if now >= epoch start time + 30s, then use `epoch number`
So, when an epoch transitions, we need to wait 30s before we start using it.  This is because, during that time, the nodes are in a transitionary state, and some may think they're on the next epoch, and some on the previous epoch.  By waiting 30s to send the new epoch, we give the nodes time to retrieve the new state.  Once 30s has elapsed, the nodes should all have seen and advanced to the new epoch, and it should be safe to send the new epoch.
So this PR removes the setTimeout that sets the new epoch number.  Instead, it looks at the epoch transition time from the chain, and starts to use the new epoch 30s after that has elapsed.  
This is better …
> LIT-3688 - Handle more cases for talking to the lit nodes across epoch transitions

- packages/auth-helpers/src/lib/resources.ts
- packages/auth-helpers/src/lib/utils.spec.ts
- packages/auth-helpers/src/lib/utils.ts
Extract the function out and add unit tests for this https://github.com/LIT-Protocol/js-sdk/pull/562
---
1. Takes out '0x' and makes the string 64 characters long.
2. Adds zeros to make short strings 64 characters.
3. Don't change valid 64-character hex strings.
4. Returns '*' as is.
5. Returns the original if it has bad hex characters.
6. Doesn't change 64-character strings.
7. Adds zeros to make short hex strings 64 characters.
8. Returns the original if it partly matches hex.
9. Throws an error if the string is too long.
> feat: extract `formatPKPResource` and add unit tests

- packages/auth-helpers/src/lib/resources.ts
- packages/auth-helpers/src/lib/utils.spec.ts
- packages/auth-helpers/src/lib/utils.ts
This PR adds 
* auto-padding of leading 0's to the LitPKPResource id to make it a 32 byte hex string.
* remove 0x prefix if it's present.  a lot of users get burned by this.
This is the result of a user report.  The user sent this in a request, as their resource ability requests: 
```
"resourceAbilityRequests\":[{\"resource\":{\"resource\":\"694d50052e0ca3e79e432024bc43ad654acd8ba0919e6ac820b720962bb2e4\",\"resourcePrefix\":\"lit-pkp\"},\"ability\":\"pkp-signing\"}]
```
They got an error back:
```
validation error: Could not find requested resource PKPNFT(PKPNFTResource { token_id: "00694d50052e0ca3e79e432024bc43ad654acd8ba0919e6ac820b720962bb2e4" }) in the resourceAbilityRequests
```
The core problem seems to be, that in the nodes, we calculate the tokenId from the PKP Pubkey via a …
> add padding to LitPkpResource

- packages/constants/src/lib/constants/constants.ts
Replacement for Sepolia's RPC url with one from https://www.publicnode.com/
Earlier one isn't functional
Can try to send a transaction,
```
let rpc = LIT_CHAINS["sepolia"].rpcUrls[0];
const provider = new ethers.providers.JsonRpcProvider(
rpc
);
const signer = new ethers.Wallet(privateKey1, provider);
const unsignedTransaction = {
to: "0x291B0E3aA139b2bC9Ebd92168575b5c6bAD5236C",
value: 2,
gasLimit: "50000",
gasPrice: (await signer.getGasPrice()).toHexString(),
nonce: await signer.getTransactionCount(
signer.getAddress()
),
};
const tx = await signer.sendTransaction(unsignedTransaction);
const receipt = tx.wait();
console.log(tx)
```
> fix: updated sepolia rpc

- packages/core/src/lib/lit-core.ts
Increasing `EPOCH_PROPAGATION_DELAY` to 45s for the nodes to update to the new epoch before using the new epoch
> fix: increase `EPOCH_PROPAGATION_DELAY` to 45s

- packages/core/src/lib/lit-core.ts
Adding Datil to `NETWORKS_REQUIRING_SEV`
> fix: missing SEV check for Datil

- packages/contracts-sdk/src/lib/contracts-sdk.ts
This PR removes the hardcoded `GAS_LIMIT` constant in contracts sdk used by default when user did not provide one and replaced it with one that increases the limit by certain margin when it is a minting transaction
> feat: replace hardcoded gas limit with calculated one including margin

- packages/core/src/lib/lit-core.ts
The issue was just mixing of seconds and milliseconds.  This PR just makes the comparisons all use seconds since that's the highest resolution we get from the chain.  I did test it myself and saw that the new epoch kicked in after 45s.
This replaces https://github.com/LIT-Protocol/js-sdk/pull/595 which has the same fix, but additional debug statements, and also a ton of changed files because i published a test build under the "chris" tag.
To test this, I ran it against datil-test during epoch transition.  I kicked off 300 sigs just before the transition started, and i got 300 successed.  I tried the same thing on v6.4.3 which doesn't have this fix and got about 6 "failed to verify signature" errors.  so i think this finally fixes this problem.
> Fix the issue with the epoch propagation delay

- packages/contracts-sdk/src/lib/contracts-sdk.ts
- packages/core/src/lib/lit-core.ts
The https://github.com/LIT-Protocol/js-sdk/pull/567 PR seems to have a bug in it that multiplies the gas limit by 110 instead of increasing it by 10%.  This is fixed by adding a division by 100 after the multiplication, which results in a 10% increase
Edit: this PR also adds a fix to the epoch delay, to make it work with the tests.  It works fine on live networks, but in the tests, when we try to use epoch 2, the delay hasn't passed yet, so we try to use epoch 1.  but epoch 1 is the first epoch and has no peers in it.  so the signing process fails in the tests.  the nodes go "i don't know about that peer".  so i put in a fix to only apply the delay if epochNumber >= 3.
> divide by 100 after multiplying by 110 to get a 10% increase

- local-tests/setup/session-sigs/get-lit-action-session-sigs.ts
- local-tests/tests/wrapped-keys/testFailEthereumSignTransactionWrappedKeyInvalidDecryption.ts
- packages/constants/src/lib/constants/constants.ts
- packages/constants/src/lib/constants/mappers.ts
- packages/lit-node-client-nodejs/src/lib/lit-node-client-nodejs.ts
- packages/types/src/lib/interfaces.ts
- packages/wrapped-keys/src/lib/lit-actions-client/export-private-key.ts
- packages/wrapped-keys/src/lib/lit-actions-client/generate-key.ts
- packages/wrapped-keys/src/lib/lit-actions-client/sign-message.ts
- packages/wrapped-keys/src/lib/lit-actions-client/sign-transaction.ts
By default, we will always fetch the IPFS content for the datil mainnet network. Other network can specify to overwrite by passing it the `ipfsOptions` param to the `executeJs`, `getPkpSessionSigs` and `getLitActionSessionSigs` functions.
This is where we change the [default](https://github.com/LIT-Protocol/js-sdk/pull/609/files#diff-f0af9d412918612361cd43d65265f31c219f32b98baaafe4f3eb98c9aea221f9R54).
Also added `FALLBACK_IPFS_GATEWAYS` for fallback gateways, here's the speed test from the UK
> feat: add `GLOBAL_OVERWRITE_IPFS_CODE_BY_NETWORK`

- packages/core/src/lib/lit-core.ts
Fixes an issue where we send the `sessionSigs` map to all nodes when performing network operations where we should only be sending a single value as the `authSig` from this mapping.
This fix is a stop gap as we need a `ParamsValidator` which will perform the following operations
- Check that all properties required for a network operation are defined
- If all required properties are not found throw an exception
-  Perform basic type assertion that required properties are of the correct type
- Check for properties which are not relevant for a given network operation and remove them
> Fix request params sent to nodes

- local-tests/tests/wrapped-keys/testSignTransactionWithSolanaEncryptedKey.ts
- packages/wrapped-keys/src/lib/lit-actions-client/constants.ts
- packages/wrapped-keys/src/lib/litActions/ethereum/src/signMessageWithEthereumEncryptedKey.js
- packages/wrapped-keys/src/lib/litActions/ethereum/src/signTransactionWithEthereumEncryptedKey.js
- packages/wrapped-keys/src/lib/litActions/solana/src/signMessageWithSolanaEncryptedKey.js
- packages/wrapped-keys/src/lib/litActions/solana/src/signTransactionWithSolanaEncryptedKey.js
Currently Solana Wrapped Keys `signTransactionWithEncryptedKey()` always returns a signed encoded transaction. Which works when the Lit Action isn't broadcasting the tx as the user can broadcast the return value. But in cases where the Lit Action should broadcast the transaction it should return the **transaction signature** which can be used by the user to confirm the transaction status:
```
const status = await solanaConnection.getSignatureStatus(signedTx); // { context: { apiVersion: '2.0.5', slot: 321490377 }, value: { confirmationStatus: 'confirmed', confirmations: 0, err: null, slot: 321490377, status: { Ok: null } } }
const confirmation = await solanaConnection.confirmTransaction(signedTx); // { context: { slot: 321490379 }, value: { err: null } }
```
Return transactionSignature …
> Feat: Return Solana tx sig from Wrapped Keys

- packages/core/src/lib/lit-core.ts
- packages/logger/src/lib/logger.spec.ts
- packages/logger/src/lib/logger.ts
Adds functionality to fetch logs based on `requestId` such that logs from an active sdk connection can be looked up and returned. Logs are currently stored in memory but can be stored in `local storage` as well with some minor updates to tail deletion of logs as new logs are added.
Below is an example of querying logs
```js
let ids = devEnv.litNodeClient.getRequestIds();
console.log('request ids', ids);
console.log(ids[1]);
const logs = devEnv.litNodeClient.getLogsForRequestId(ids[1]);
console.log(logs);
```
example output: 
```ascii
[
'[Lit-JS-SDK v6.4.10]\x1B[36m[DEBUG]\x1B[0m [core] [id: 6e232dc7de4e] sendCommandToNode with url https://173.208.0.151:443/web/execute/v1 and data {\n' +
'  "code": "KGFzeW5jICgpID0+IHsKICAgICAgY29uc3Qgc2lnU2hhcmUgPSBhd2FpdCBMaXRBY3Rpb25zLnNpZ25FY2RzYSh7CiAg …
```
> dev: Add id fetching to logger api and expose in lit core

- packages/wrapped-keys/build-bc.sh
Add support for different OS type when executing `sed` command in a shell script. Previously it was only working on Linux (GNU sed), but we need it to work on macOs as well (BSD sed)
> fix: add support for different os types for the sed shell script command

- packages/auth-helpers/src/lib/models.ts
- packages/auth-helpers/src/lib/recap/recap-session-capability-object.spec.ts
- packages/auth-helpers/src/lib/recap/recap-session-capability-object.ts
- packages/lit-node-client-nodejs/src/lib/lit-node-client-nodejs.ts
- packages/types/src/lib/models.ts
addRateLimitAuthSig is not used anywhere in the codebase. It was a leftover from the auth unification project that we forgot to remove.
> chore: remove unused `rateLimitAuthSig` function

- packages/contracts-sdk/src/lib/contracts-sdk.ts
by definition minimum we mean "at least we must have this many validators"
> fix: should be `<` as opposed to `<=`

- packages/contracts-sdk/src/lib/contracts-sdk.ts
- packages/types/src/lib/types.ts
This PR is a suggestion for https://github.com/LIT-Protocol/js-sdk/pull/628
Add new type for the contract names instead of string[]
> feat: add type improvement

- local-tests/setup/shiva-client.ts
- local-tests/setup/tinny-person.ts
- packages/contracts-sdk/src/lib/addresses.ts
- packages/contracts-sdk/src/lib/contracts-sdk.ts
- packages/core/src/lib/lit-core.ts
- packages/misc/src/lib/misc.ts
- packages/pkp-ethers/src/lib/pkp-ethers.ts
This PR adds `skipFetchSetup` to `StaticJsonRpcProvider`s instances to avoid no network error in webpack environments such as next.js backend. Explained in #538 
Backend before:
Backend after:
Note: Frontend was working fine, no changes there
> feat: add skipFetchSetup to ethers providers constructor

- packages/wrapped-keys/src/lib/api/sign-message-with-encrypted-key.ts
- packages/wrapped-keys/src/lib/service-client/client.ts
- packages/wrapped-keys/src/lib/service-client/types.ts
- packages/wrapped-keys/src/lib/service-client/utils.ts
- Updated logging logic in wrapped-keys so that we now log HTTP error codes for failed requests, and `error.cause` when it is defined.
- `error.cause` should give us insights into the _reason_ why a `fetch failed` error is thrown; previously all we saw in logs was the string `fetch failed`, because fetch puts the really useful info in a `cause` property on the error
- Added requestId generation and logging to the wrapped-keys service client.  Error logs now include our _internal_ request id, and we send that request ID to the API backend in the `x-correlation-id` header, which provides integration with cloudwatch and `pino-lambda` (for service logs) -- It was just an added benefit that it was also the simplest way (identical logic for GET and POST routes)
Example output from …
> LIT-3896 - Better error logs & request id tracking and submission for wrapped-keys service client

- packages/contracts-sdk/src/lib/contracts-sdk.ts
> fix: `rpcUrl` should be used when provided in the `getStakingContract` function

- packages/wrapped-keys-lit-actions/src/lib/solana/signTransactionWithSolanaEncryptedKey.js
Fix wrong encoding - it should be `base58` instead of `base64`.
As per @spacesailor24 comment for the following Lit Action:
```js
const transaction = Transaction.from(
Buffer.from(unsignedTransaction.serializedTransaction, 'base64')
);
transaction.sign(solanaKeyPair);
const signature = transaction.signature.toString('base64');
if (broadcast) {
const solanaConnection = new Connection(
clusterApiUrl(unsignedTransaction.chain),
'confirmed'
);
const transactionSignature = await solanaConnection.sendRawTransaction(
transaction.serialize()
);
Lit.Actions.setResponse({ response: transactionSignature });
} else {
Lit.Actions.setResponse({ response: signature });
}
```
When broadcast is true, transactionSignature will be base58 encoded, but when false, signature is base64 encoded
> fix: wrong encoding - should be `base58` instead of `base64`

- packages/contracts-sdk/src/lib/contracts-sdk.ts
Fix for this: (Unable to connect using the LitContracts client)
Due to this was added in the PR:
https://github.com/LIT-Protocol/js-sdk/pull/639/files#diff-2dcc2c94e7788b1bbaef5e6cf9158025a2580d238f807bd3cb923bbe355eb47bR401-R406
And we need this patch for the following affected versions:
- https://github.com/LIT-Protocol/js-sdk/pull/648
- https://github.com/LIT-Protocol/js-sdk/pull/658
- https://github.com/LIT-Protocol/js-sdk/pull/666
Anything <= 6.5.3 are working
> fix: `connection` is undefined when connecting to LitContracts

- packages/contracts-sdk/src/lib/contracts-sdk.ts
fix: should respect the `debug` flag when it's off
> fix: should respect the `debug` flag when it's off

- packages/lit-node-client-nodejs/src/lib/lit-node-client-nodejs.ts
This PR requires only the threshold nodes to sign sessions as it uses BLS, not ECDSA. Also fixes a check that was discarding node responses with an index value of `0` because it is considered `falsy` in JS
> feat: only wait for threshold nodes when signing session keys

- packages/crypto/src/lib/crypto.ts
Remove unused case 218 and provide more details on how it works
> feat(bls): remove case 218 as we don't use it

- packages/lit-node-client-nodejs/src/lib/lit-node-client-nodejs.ts
Improve `getSessionSigs` jsDoc
> doc(getSessionSigs): improve jsDocs

- package.json
- packages/auth-browser/package.json
- yarn.lock
Fix
```
Error: Cannot find module '@lit-protocol/contracts'
Require stack:
/node_modules/@lit-protocol/constants/src/lib/constants/mappers.js
```
> fix: add `@lit-protocol/contracts` to auth-browser peer dep

- packages/core/jest.config.ts
- packages/core/src/lib/lit-core.spec.ts
- packages/core/src/lib/lit-core.ts
This is just a backport of #727 for our v6 SDK
Added some safety measures when syncing blockhash. More specifically:
- verify fetch response from block-indexer is successful to avoid using error responses with `undefined` `blockhash`es
- use previous-to-last blockhash from public providers on fallback to avoid using a blockhash not yet propagated to nodes
- use block `timestamp` instead of user one as that is the one that defines if `blockhash` is still valid
> fix: blockhash syncing v6 - 2

- .github/workflows/ci.yml
- package.json
- yarn.lock
Right now we have a hardcoded lit actions commit hash.  This will try to pull down the latest and use that, instead.  Github artifacts expire 30 days after publishing so this is prob why CI broke.  
This is an extension of https://github.com/LIT-Protocol/js-sdk/pull/736 where I debugged the underlying issue (well, multiple issues) and found that the commit hash was the first broken thing (because the artifact gets deleted after 30 days), and then we needed to change the `rust/lit-node-build-commit-hash` ubuntu version to 22, which finally fixed it.
This uses our own fork of an action that will pull the latest hash from the lit-assets repo, which is here: https://github.com/LIT-Protocol/last-successful-build-action
> Get latest commit hash for shiva in CI

- package.json
- packages/constants/src/lib/constants/constants.ts
- yarn.lock
Waiting for [accs-schemas release](https://github.com/LIT-Protocol/accs-schemas/pull/27)
> Add `coreDao`, `zkCandySepoliaTestnet`, and `filecoinCalibrationTestnet`

- packages/wrapped-keys/src/lib/api/utils.spec.ts
This pull request fixes the failing test in `packages/wrapped-keys/src/lib/api/utils.spec.ts`, which currently expects an array of access control conditions. However, the actual implementation of `getPkpAccessControlCondition` returns a **single** `AccsDefaultParams` object, as documented:
```packages/wrapped-keys/src/lib/api/utils.ts
/**
*
* Creates the access control condition used to gate the access for Wrapped Key decryption
*
* @param { string } pkpAddress - The wallet address of the PKP which can decrypt the encrypted Wrapped Key
*
* @returns { AccsDefaultParams } - The access control condition that only allows the PKP address to decrypt
*/
export function getPkpAccessControlCondition(
pkpAddress: string
): AccsDefaultParams {
if (!ethers.utils.isAddress(pkpAddress)) {
throw new …
```
> fix #760 wrapped-keys test to expect a single ACC object instead of an array

- packages/logger/src/lib/logger.spec.ts
- packages/logger/src/lib/logger.ts
This pull request fixes the logger test so that it no longer fails when importing `LOG_LEVEL` from `logger.ts`. Previously, there was a mismatch between `LOG_LEVEL` (a constant from `@lit-protocol/constants`) and `LogLevel` (an enum). This change ensures that both references can coexist, while favoring `LOG_LEVEL` for future compatibility.  
Additionally, the test that checks creation timestamps (`should order logs based on logger creation timestamp`) has been corrected to compare `loggerA.timestamp` and `loggerB.timestamp` properly, instead of incorrectly matching a numeric timestamp against string IDs.
**Related Issue:**  
- Fix [#758](https://github.com/LIT-Protocol/js-sdk/issues/758)
- **Locally**:  
- Ran `npx nx run logger:test --coverage` and all tests passed without TypeScript …
> fix #758 logger tests

- .github/workflows/ci.yml
Updated Rust in CI to 1.83.0 to fix wasm build issues.
> fix(ci): update Rust version to 1.83.0 for wasm compatibility

- packages/lit-node-client-nodejs/src/lib/lit-node-client-nodejs.ts
Log encryption metadata to compare against the node logs when decryption fails within Lit Actions since the nodes don't format the ACC in exactly the same manner as the SDK.
Just logs no tests required
> feat: Log encryption metadata to compare against node logs

- packages/constants/src/index.ts
- packages/contracts-sdk/src/index.ts
- packages/contracts-sdk/src/lib/contracts-sdk.ts
- packages/contracts-sdk/src/lib/price-feed-info-manager.ts
- packages/core/src/lib/lit-core.ts
- packages/lit-node-client-nodejs/src/lib/lit-node-client-nodejs.ts
- packages/types/src/lib/ILitNodeClient.ts
Somewhere in all the code shuffling leading up to our current Naga branch, logic that re-fetched node prices was lost.  This PR adds it back in.
- Moved price feed info fetching to `price-feed-info-manager` module, which is responsible for handling caching of fetched data and concurrent requests to fetch the data
- Only 1 fetch promise can be run at a time; concurrent requests chain on any existing pending promise that is already loading price feed data
- Only fetches new data if it has been > 3 seconds since last fetch; since the nodes only update their on-chain price intermittently, this seems like a reasonable constraint to avoid hammering RPC multiple times per second even though the nodes only sync every few seconds.
- Updated static method `getPriceFeedInfo()` on LitContracts class …
> LIT-4207 - Implement node price re-fetching when running lit node commands

- packages/lit-node-client-nodejs/src/lib/helpers/validate-bls-session-sigs.spec.ts
This PR fixes the failing test in `packages/lit-node-client-nodejs/src/lib/helpers/validate-bls-session-sigs.spec.ts`. The test currently throws:
```
Invalid SIWE message. Missing expirationTime or issuedAt.
```
because the `SiweMessage` created in the test has `expirationTime` but no `issuedAt`. According to `blsSessionSigVerify` logic in `validate-bls-session-sig.ts`, **both** `issuedAt` and `expirationTime` must be present.
By adding `issuedAt: new Date().toISOString()` to the `new SiweMessage({ ... })`, the test now passes without error, aligning with EIP-4361 which typically includes `issuedAt`.
**Related Issue**: 
fix https://github.com/LIT-Protocol/js-sdk/issues/771
---
---
1. **Local**  
- Ran `npx nx run lit-node-client-nodejs:test` locally after adding `issuedAt`.  
- Confirmed …
> Fix `lit-node-client-nodejs` test by adding `issuedAt` to SIWE message

- local-tests/test.ts
- local-tests/tests/testPruneRLI.ts
- packages/contracts-sdk/src/lib/contracts-sdk.ts
Add a pruneExpired feature for RLI to facilitate this PR:
https://github.com/LIT-Protocol/lit-scheduled-tasks/pull/15/files
> feat: add `pruneExpired` helper function

- .github/workflows/health-checks.yml
Pull request refactors the E2E Tests and Health Checks workflow.
**The key changes are:**
- Removed Matrix Strategy: The workflow no longer uses a matrix strategy. Instead, each job now performs a single repository checkout and dependency installation, then runs the network health checks as **sequential steps.** 
- Updated Default Branch: The default branch for the `naga-health-check job` has been updated from `naga` to `master` to align with current repository standards.
> [INF-607] Follow Up: Add workflow to e2e Tests

- README.md
> [Alpha] [Naga] To be released

- .gitignore
- e2e/src/e2e.spec.ts
- e2e/src/helper/auth-contexts.ts
- e2e/src/helper/tests/encrypt-decrypt-flow.ts
- e2e/src/helper/tests/execute-js.ts
- e2e/src/helper/tests/pkp-encrypt-decrypt.ts
- e2e/src/helper/tests/pkp-sign.ts
- e2e/src/helper/tests/view-pkps-by-address.ts
- e2e/src/helper/tests/view-pkps-by-auth-data.ts
- e2e/src/init.ts
- e2e/src/tickets/custom-auth.spec.ts
- packages/networks/src/networks/vNaga/shared/factories/BaseModuleFactory.ts
- packages/networks/src/networks/vNaga/shared/managers/api-manager/e2ee-request-manager/E2EERequestManager.ts
Custom auth E2E tests were producing false-positive results. It was working because it was using the cached Alice's delegation auth sig instead of using a fresh PKP.
- Fixed the custom auth test to use Eve's PKP instead of Alice.
- Updated the custom auth validation ipfs cid [QmTdTemgWBYS76ACdZPttsve6edukyXjCdsNYNK1QDeXKY](https://explorer.litprotocol.com/ipfs/QmTdTemgWBYS76ACdZPttsve6edukyXjCdsNYNK1QDeXKY)
- Disabled some custom auth tests for the time being, will need to have follow up PRs for that.
This PR depends on the hardcoded keysets fixes [here](https://github.com/LIT-Protocol/js-sdk/pull/880)
```bash
bun test e2e/src/tickets/custom-auth.spec.ts --timeout 500000
```
> [Bug] Fix False Positive Custom Auth Tests

- .github/workflows/e2e.yml
enable the E2E workflow to run on the `naga` branch
> chore(ci): run e2e workflow on naga branch

- .github/workflows/prerelease.yml
- .github/workflows/release.yml
CI is failing build, remove NX Daemon to match the e2e CI
> chore(workflows): remove NX_DAEMON environment variable from build steps
